---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: homelab
  namespace: flux-system
spec:
  interval: 30m
  url: https://gitlab.com/sami-group/homelab
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include clusters directory
    !/clusters
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-cluster
  namespace: flux-system
spec:
  interval: 30m
  path: ./clusters/home/flux
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: homelab
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-cluster
  namespace: flux-system
spec:
  interval: 5m
  path: ./clusters/home/apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  dependsOn:
    - name: flux-cluster
