---
collections:
  - name: ansible.utils
  - name: ansible.posix
  - name: community.general
  - name: community.windows
  - name: community.docker
  - name: community.sops
  - name: kubernetes.core
  - name: sami_shakir.public_collection
    source: https://gitlab.com/sami-group/ansible/collections/public.git
    type: git
