---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: traefik
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  values:
    # image:
    #   name: ghcr.io/k8s-at-home/traefik
    globalArguments:
      - "--api.insecure=true"
      - "--global.sendanonymoususage=false"
      - "--global.checknewversion=false"
      - "--serverstransport.insecureskipverify=true"
      # - "--providers.kubernetesingress.ingressclass=traefik"
      # - "--metrics.prometheus=true"
      # - "--metrics.prometheus.entryPoint=metrics"
      # - "--entryPoints.websecure.forwardedHeaders.trustedIPs=10.0.0.0/8,192.168.0.0/16,172.16.0.0/12,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,104.16.0.0/13,104.24.0.0/14,108.162.192.0/18,131.0.72.0/22,141.101.64.0/18,162.158.0.0/15,172.64.0.0/13,173.245.48.0/20,188.114.96.0/20,190.93.240.0/20,197.234.240.0/22,198.41.128.0/17,2400:cb00::/32,2606:4700::/32,2803:f800::/32,2405:b500::/32,2405:8100::/32,2a06:98c0::/29,2c0f:f248::/32"
    additionalArguments:
      - "--log.level=DEBUG"
      # - "--providers.kubernetesingress.ingressendpoint.ip=${SVC_TRAEFIK_ADDR}"
      # - "--providers.kubernetesingress.allowexternalnameservices=true"
      # - "--providers.kubernetescrd.allowexternalnameservices=true"
    deployment:
      # kind: Deployment
      enabled: true
      replicas: 1
    ports:
      web:
        redirectTo: websecure
      websecure:
        tls:
          enabled: true
          options: "default"
      # traefik:
      #   expose: true
      # metrics:
      #   port: 8082
      #   expose: true
      #   exposedPort: 8082
    ingressRoute:
      dashboard:
        enabled: false
    providers:
      kubernetesCRD:
        enabled: true
        ingressClass: traefik-external
      kubernetesIngress:
        enabled: true
        publishedService:
          enabled: false
    rbac:
      enabled: true
    service:
      enabled: true
      type: LoadBalancer
      spec:
        loadBalancerIP: 10.10.0.81
        # externalTrafficPolicy: Local
      # annotations:
      #   metallb.universe.tf/address-pool: dev-infra

    # logs:
    #   general:
    #     format: json
    #     level: DEBUG
    #   access:
    #     enabled: true
    #     format: json
    # ingressClass:
    #   enabled: true
    #   isDefaultClass: true
    #   fallbackApiVersion: v1
    # tlsOptions:
    #   default:
    #     minVersion: VersionTLS12
    #     maxVersion: VersionTLS13
    #     sniStrict: true
    # pilot:
    #   enabled: false
    # experimental:
    #   plugins:
    #     enabled: false
    # resources:
    #   requests:
    #     memory: 100Mi
    #     cpu: 500m
    #   limits:
    #     memory: 500Mi
