---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: traefik-forward-auth-secrets
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
  target:
    name: traefik-forward-auth-secrets
    creationPolicy: Owner
  dataFrom:
    - find:
        name:
          regexp: "^GOOGLE"
    - find:
        name:
          regexp: "^DOMAIN"
    - find:
        name:
          regexp: "^OAUTH_SECRET"
    - find:
        name:
          regexp: "^GMAIL_ADDRESS"
