---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  # install:
  #   createNamespace: true
  #   remediation:
  #     retries: 3
  # upgrade:
  #   remediation:
  #     retries: 3
  values:
    podAnnotations:
      secret.reloader.stakater.com/reload: prowlarr-secrets
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: ghcr.io/onedr0p/prowlarr-nightly
      tag: 1.8.4.3883@sha256:e4262089645defdcf731c37cc0546b3897fea0a8956ab67f80f33fee8d2af724
    env:
      TZ:
        valueFrom:
          secretKeyRef:
            name: common-secrets
            key: TZ
    service:
      main:
        annotations:
          external-dns.alpha.kubernetes.io/hostname: prowlarr.shaklab.com
          external-dns.alpha.kubernetes.io/target: ipv4.shaklab.com
        ports:
          http:
            port: 9696

    # dnsConfig:
    #   options:
    #     - name: ndots
    #       value: "1"

    # podSecurityContext:
    #   runAsUser: 0
    #   runAsGroup: 0
    persistence:
      config:
        enabled: true
        existingClaim: prowlarr-config
      # shared:
      #   enabled: true
      #   type: emptyDir
      #   mountPath: /shared
      # backups:
      #   enabled: true
      #   mountPath: /config/Backups
      #   # mountOptions: nolock
      #   type: nfs
      #   server: "${PRIMARY_NFS_SERVER}"
      #   path: "${NFS_KUBERNETES_PATH}/backups/prowlarr"

    # ingress:
    #   main:
    #     enabled: true
    #     ingressClassName: "traefik"
    #     annotations:
    #       traefik.ingress.kubernetes.io/router.entrypoints: websecure
    #       traefik.ingress.kubernetes.io/router.middlewares: networking-rfc1918-ips@kubernetescrd
    #       hajimari.io/enable: "true"
    #       hajimari.io/group: "Media"
    #       hajimari.io/icon: "cloud-search"
    #     hosts:
    #       - host: &host "prowlarr.${SECRET_DOMAIN}"
    #         paths:
    #           - path: /
    #     tls:
    #       - secretName: "wildcard-internal-${SECRET_DOMAIN/./-}-tls"
    #         hosts:
    #           - *host

    # resources:
    #   requests:
    #     cpu: 15m
    #     memory: 443M
    #   limits:
    #     memory: 454M
