---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cross-seed
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
  target:
    name: cross-seed-secret
    creationPolicy: Owner
    template:
      templateFrom:
        - configMap:
            name: cross-seed-config-tpl
            items:
              - key: config.js
  data:
    - secretKey: PROWLARR_API_KEY
      remoteRef:
        key: PROWLARR_API_KEY
