---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cross-seed
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: homelab-dev-container
  target:
    name: cross-seed-secret
    creationPolicy: Owner
    template:
      templateFrom:
        - configMap:
            name: cross-seed-config-tpl
            items:
              - key: config.js
  data:
    - secretKey: PROWLARR_API_KEY
      remoteRef:
        key: PROWLARR_API_KEY
