---
ubuntu_img:
  version_number: 22.04
  cpu_arch: amd64
  release: current

ubuntu_img_url: https://cloud-images.ubuntu.com/releases/{{ ubuntu_img.version_number }}/release/ubuntu-{{ ubuntu_img.version_number }}-server-cloudimg-{{ ubuntu_img.cpu_arch }}-wsl.rootfs.tar.gz

wsl_instance_name: "Ubuntu-{{ ubuntu_img.version_number }}-template"
img_dir: "{{ ansible_env.TEMP }}\\wsl"
wsl_install_location: C:\wsl\instances\{{ wsl_instance_name }}
