---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: th3cookie@gmail.com
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            email: th3cookie@gmail.com
            apiKeySecretRef:
              name: cloudflare-api-key
              key: CLOUDFLARE_API_KEY
        selector:
          dnsZones:
            - shaklab.com
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: th3cookie@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          cloudflare:
            email: th3cookie@gmail.com
            apiKeySecretRef:
              name: cloudflare-api-key
              key: CLOUDFLARE_API_KEY
        selector:
          dnsZones:
            - shaklab.com
