---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-xteve
  namespace: flux-system
spec:
  path: ./kubernetes/home/apps/media/xteve/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  wait: true
  interval: 1h
  retryInterval: 1m
  timeout: 5m
