stages:
  - debug
  - build

debug vars:
  stage: debug
  # Set to true when you want to debug the pipeline (or add this var when manually triggering)
  # variables:
  #   DEBUG_PIPELINE: "true"
  # Run this only when setting `DEBUG_PIPELINE` evaluates true
  rules:
    - if: '$DEBUG_PIPELINE =~ /^(y|yes|true|1)$/i'
  script:
    - doppler run -- ./docker/bin/doppler-test
    - env

build docker image:
  stage: build

  image:
    name: docker

  services:
    - docker:dind

  # Only run build if Dockerfile changes
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - changes:
      - docker/**/*
      - provision/ansible/requirements.yml
      - provision/ansible/roles/requirements.yml
      - requirements.txt

  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin

  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=""
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
        tag=":$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - docker build --pull -t "$CI_REGISTRY_IMAGE" -f docker/Dockerfile .
    - docker push "$CI_REGISTRY_IMAGE"

  after_script:
    - docker logout
