stages:
  - debug
  - build
  - deploy

debug vars:
  stage: debug
  # Run this only when setting `DEBUG_PIPELINE` evaluates true
  rules:
    - if: '$DEBUG_PIPELINE =~ /^(y|yes|true|1)$/i'
  script:
    - echo "Doppler test:"
    - doppler run -- ./bin/doppler-test
    - echo "ENV is:"
    - env

build docker image:
  stage: build

  image:
    name: docker

  services:
    - docker:dind

  # Only run build if Dockerfile changes
  rules:
    - changes:
      - Dockerfile
      - provision/ansible/requirements.yml
      - provision/ansible/roles/requirements.yml
      - requirements.txt

  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin

  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=""
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
        tag=":$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"

  after_script:
    - docker logout
