stages:
  - debug
  - build
  - deploy

print env vars:
  stage: debug

  environment:
    name: production
    url: https://$DOMAIN_NAME

  rules:
    # Rule if commit branch is main (no others) and run manually
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
    # Rule if scheduled
    # - if: $CI_PIPELINE_SOURCE == "schedule"

  script:
    - env

doppler test:
  stage: debug
  script:
    - doppler run -- ./bin/doppler-test
  rules:
    # Rule if commit branch is main (no others) and run manually
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual

build docker image:
  stage: build

  image:
    name: docker

  services:
    - docker:dind

  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin

  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=""
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
        tag=":$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"

  after_script:
    - docker logout

  # Only run build if Dockerfile changes
  rules:
    - changes:
      - Dockerfile
      - provision/ansible/requirements.yml
      - provision/ansible/roles/requirements.yml
      - requirements.txt
