stages:
  - debug
  - build
  - deploy

print env vars:
  stage: debug

  environment:
    name: production
    url: https://$DOMAIN_NAME

  # Run this only when setting `DEBUG_PIPELINE` env var
  rules:
    - if: $DEBUG_PIPELINE

  script:
    - env
    - echo $DEBUG_PIPELINE

doppler test:
  stage: debug
  script:
    - echo "DEBUG_PIPELINE is $DEBUG_PIPELINE"
    - |
      if [[ "$DEBUG_PIPELINE" == "True" ]]; then
        doppler run -- ./bin/doppler-test
      else
        echo "Skipping doppler test job"
      fi
  # Run this only when setting `DEBUG_PIPELINE` env var
  rules:
    - if: $DEBUG_PIPELINE

build docker image:
  stage: build

  image:
    name: docker

  services:
    - docker:dind

  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin

  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=""
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
        tag=":$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"

  after_script:
    - docker logout

  # Only run build if Dockerfile changes
  rules:
    - changes:
      - Dockerfile
      - provision/ansible/requirements.yml
      - provision/ansible/roles/requirements.yml
      - requirements.txt
