---
#-------------------------------------#
# Pre-tasks run before anything else! #
#-------------------------------------#
- hosts: minikube
  # Special tag "always" -> https://docs.ansible.com/ansible/latest/user_guide/playbooks_tags.html#special-tags-always-and-never
  tags: [ "always" ]
  gather_facts: false
  tasks:
    - import_tasks: tasks/pre-all.yml

################
### minikube ###
################

- name: Configure minikube cluster
  hosts: minikube
  remote_user: "{{ vm.user | default(main_user) }}"  # Login as user and become root
  become: true

  pre_tasks:  &pre_tasks   # Anchors to re-use the code later. No point duplicating code.

    # This is to get the PUID and PGID variables to use later in multiple areas
    - name: Get user info or create a user if one doesn't exist
      import_tasks: tasks/linux/pre_tasks.yml
      tags: ["always"]

  roles:

    - geerlingguy.docker
    - gantsign.minikube
    - geerlingguy.helm  # Install helm on minikube nodes to deploy charts in ansible
    - andrewrothstein.kubectl

  tasks:

    - name: Setup user to run docker commands
      import_tasks: tasks/minikube/user.yml

    - name: Install package dependencies
      import_tasks: tasks/minikube/apt.yml

- name: Deploy Helm Charts
  hosts: minikube
  remote_user: "{{ vm.user | default(main_user) }}"  # Login as user and become root
  become: false

  pre_tasks: *pre_tasks

  tasks:

    - name: Install pip dependencies
      import_tasks: tasks/minikube/pip.yml

    - name: Setup aliases and functions in bash environment
      import_tasks: tasks/minikube/bashrc.yml

    - name: Start minikube
      shell: minikube start

    - name: deploy k8s manifests
      import_role:
        name: geerlingguy.k8s_manifests # Deploys everything inside file - `group_vars/k3s/vars.yml` lines - `43-46` variables - `k8s_*`
      tags: ['nfs', 'k8s_manifests']

    - name: Deploy Helm Charts
      import_tasks: tasks/k3s/deploy_helm_charts.yml
