---
- name: Test Playbook

  pre_tasks:

    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/vars/config.yml"
      # Special tag 'always' -> https://docs.ansible.com/ansible/latest/user_guide/playbooks_tags.html#special-tags-always-and-never
      tags: ["always"]

    # This is to get the PUID and PGID variables to use later in multiple areas
    - name: Get user info or create a user if one doesn't exist
      import_tasks: tasks/linux/pre_tasks.yml
      tags: ["always"]

  handlers:

    - import_tasks: handlers/proxmox.yml
    - import_tasks: handlers/docker.yml

##################
### Start here ###
##################

  hosts: docker
  become: true

  # roles:
  #   - role: role-here

  tasks:
    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts

    # - name: Import task from anywhere
    #   import_tasks: tasks/wsl/configure_wsl.yml
