---
###################
### k3s cluster ###
###################

- name: Configure k3s cluster
  hosts: k3s
  become: true

  pre_tasks:  &pre_tasks   # Anchors to re-use the code later. No point duplicating code.

    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/vars/config.yml"
      # Special tag 'always' -> https://docs.ansible.com/ansible/latest/user_guide/playbooks_tags.html#special-tags-always-and-never
      tags: ["always"]

    # This is to get the PUID and PGID variables to use later in multiple areas
    - name: Get user info or create a user if one doesn't exist
      import_tasks: tasks/linux/pre_tasks.yml
      tags: ["always"]

  handlers:

    - import_tasks: handlers/k3s.yml

  roles:

    - role: k3s/prereq
    - role: k3s/download
    - role: k3s/raspberrypi

- name: Configure k3s - Main VM's
  hosts: k3s_main
  become: yes

  pre_tasks: *pre_tasks

  roles:

    - role: k3s/master
    - geerlingguy.helm  # Install helm on k3sm nodes to deploy charts in ansible

- name: Configure k3s - Node VM's
  hosts: k3s_node
  become: yes

  pre_tasks: *pre_tasks

  roles:

    - role: k3s/node

- name: Install/configure Helm/kubectl on control node (i.e. the host you are running this playbook on, soz <3)
  hosts: wsl  # Run on wsl as that is what I use
  become: yes

  pre_tasks: *pre_tasks

  roles:

    - andrewrothstein.kubectl
    - geerlingguy.helm

  tasks:

    - name: Copy kube config
      import_tasks: tasks/k3s/kubectl_helm_config.yml

- name: Deploy Helm Charts
  hosts: k3sm1
  become: false

  pre_tasks: *pre_tasks

  tasks:

    - name: Setup aliases and functions in bash environment
      import_tasks: tasks/k3s/bashrc.yml

    - name: Setup dependencies
      import_tasks: tasks/k3s/dependencies.yml
      become: true

    - name: deploy k8s manifests
      import_role:
        name: geerlingguy.k8s_manifests
      tags: ['nfs', 'k8s_manifests']

    - name: Deploy Helm Charts
      import_tasks: tasks/k3s/deploy_helm_charts.yml
      tags: ["deploy_helm_charts"]
      when: ansible_host == hostvars[groups['k3s_main'][0]]['ansible_host'] | default(groups['k3s_main'][0])  # We only want to deploy the chart to the k3sm1 (k3s-main-1) node.
