---
####################################
### Run tasks on all linux hosts ###
####################################

- name: Run tasks on all linux hosts
  hosts: docker wsl proxmox
  become: true
  # Load in our default and vaulted vars
  vars_files:
    - vars/vault.yml
  tasks:
    - name: Set timezone
      timezone:
        name: "{{ tz }}"
