---
- name: Test Playbook

  # Load in our default and vaulted vars as part of the play (it needs to be done here and not inside the tasks)
  vars_files:
    - vars/vault.yml

  pre_tasks:
    # Allow user to override defaults with their custom config file.
    # include_vars has a higher precedence than vars_files above, so import these files as overrides.
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/vars/config.yml"
      # Special tag 'always' -> https://docs.ansible.com/ansible/latest/user_guide/playbooks_tags.html#special-tags-always-and-never
      tags: ["always"]

    # This is to get the PUID and PGID variables to use later in multiple areas
    - name: Get user info or create a user if one doesn't exist
      import_tasks: tasks/linux/pre_tasks.yml
      tags: ["always"]

  # Import handlers for all tasks
  handlers:
    - import_tasks: handlers/proxmox.yml
    - import_tasks: handlers/docker.yml

##################
### Start here ###
##################

  hosts: docker
  become: true

  # roles:
  #   - create-proxmox-template-from-ubuntu-cloud-image

  tasks:
    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts

    # - name: Comment every item in /etc/environment file out - it keeps breaking windows paths in WSL, and I need those
    #   import_tasks: tasks/wsl/configure_wsl.yml
