---
#-------------------------------------#
# Pre-tasks run before anything else! #
#-------------------------------------#
- hosts: lxc
  # Special tag "always" -> https://docs.ansible.com/ansible/latest/user_guide/playbooks_tags.html#special-tags-always-and-never
  tags: [ "always" ]
  gather_facts: false
  tasks:
    - import_tasks: tasks/pre-all.yml

#-----#
# LXC #
#-----#

- name: Setup and configure dev01 Container
  hosts: dev_lxc
  tags: [ "lxc-dev_lxc" ]
  become: true

  pre_tasks:  &pre_tasks

    # This is to get the PUID and PGID variables to use later in multiple areas
    - name: Get user info or create a user if one doesn't exist
      import_tasks: tasks/linux/pre_tasks.yml
      tags: ["always"]

  roles:

    - geerlingguy.docker  # geerlingguy roles don't work in WSL - Use docker desktop WSL integration instead.
    - geerlingguy.ntp     # geerlingguy roles don't work in WSL.

  tasks:

    - name: Install OS updates and required packages
      import_tasks: tasks/wsl/install_os_packages.yml
      when: install_os_packages
      tags: [ "install_os_packages" ]

    - name: Copy git repos
      import_tasks: tasks/wsl/git.yml
      when: git
      tags: [ "git" ]

- name: Setup Gitlab Runner LXC(s)
  hosts: gitlab_runner
  tags: [ "lxc-gitlab_runner" ]
  become: true

  pre_tasks:

      # This is to get the PUID and PGID variables to use later in multiple areas
    - name: Get user info or create a user if one doesn't exist
      import_tasks: tasks/linux/pre_tasks.yml
      tags: [ "always" ]

  roles:

    - riemers.gitlab-runner
    - geerlingguy.docker
    - geerlingguy.ntp

  tasks:

    - name: Add 'gitlab-runner' user to docker group
      user:
        name: gitlab-runner
        groups: docker
        append: yes

    - name: Setup Crons
      import_tasks: tasks/lxc/gitlab-runner/setup_crons.yml

### LDAP turnkey is a WIP

# - name: Setup and configure ldap Container
#   hosts: ldap
#   tags: [ "never", "lxc-ldap" ]
#   become: true

#   pre_tasks: *pre_tasks

#   roles:

#     - geerlingguy.ntp     # geerlingguy roles don't work in WSL.

#   tasks:

#     - name: Install OS updates and required packages
#       import_tasks: tasks/wsl/install_os_packages.yml
#       when: install_os_packages
#       tags: [ "install_os_packages" ]

#     - name: Copy git repos
#       import_tasks: tasks/wsl/git.yml
#       when: git
#       tags: [ "git" ]
