---
#-------------------------------------#
# Pre-tasks run before anything else! #
#-------------------------------------#
- hosts: all
  # Special tag "always" -> https://docs.ansible.com/ansible/latest/user_guide/playbooks_tags.html#special-tags-always-and-never
  tags: [ "always" ]
  gather_facts: false
  tasks:
    - import_tasks: tasks/pre-all.yml

- name: Test Playbook

  # pre_tasks:

  #   # This is to get the PUID and PGID variables to use later in multiple areas
  #   - name: Get user info or create a user if one doesn't exist
  #     import_tasks: tasks/linux/pre_tasks.yml
  #     tags: ["always"]

  # handlers:

  #   - import_tasks: handlers/proxmox.yml
  #   - import_tasks: handlers/docker.yml

#--------------------
# Hosts Declaration -
#--------------------

  ### Docker
  # hosts: docker
  # become: true

  ### Windows
  # hosts: windows

  ### WSL
  hosts: wsl
  become: true

#--------------------
# Roles Declaration -
#--------------------

  # roles:
  #   - role: role-here

#--------------------
# Tasks Declaration -
#--------------------

  tasks:
    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts
