---
# import overrides
- hosts: proxmox lxc docker_dev
  # Special tag "always" -> https://docs.ansible.com/ansible/latest/user_guide/playbooks_tags.html#special-tags-always-and-never
  tags: [ "always" ]
  gather_facts: false
  tasks:
  - name: Include playbook configuration.
    include_vars: "{{ item }}"
    with_fileglob:
      - "{{ playbook_dir }}/vars/config.yml"

### WARNING - Needs testing on a throwaway machine first -> https://github.com/lae/ansible-role-proxmox
# - name: Setup proxmox on bare metal debian machine
#   hosts: proxmox_nodes
#   become: True

#   roles:

#     - role: lae.proxmox
#         - pve_group: all
#         - pve_reboot_on_kernel_update: true

- name: Configure Proxmox
  hosts: proxmox

  pre_tasks: &pre_tasks   # Anchors to re-use the code later. No point duplicating code.

    # This is to get the PUID and PGID variables to use later in multiple areas
    - name: Get user info or create a user if one doesn't exist
      import_tasks: tasks/linux/pre_tasks.yml
      tags: ["always"]

  roles:

    - ironicbadger.proxmox_nag_removal

  handlers:

    - import_tasks: handlers/proxmox.yml

  tasks:

    - name: Ensure proxmox host is up, if not, send a Wake-on-LAN packet
      import_tasks: tasks/proxmox/host_start.yml
      tags: ["host_start"]

    - name: Install OS updates and required packages
      import_tasks: tasks/proxmox/install_os_packages.yml
      when: install_os_packages
      tags: ["install_os_packages"]

    - name: Copy files to proxmox host
      import_tasks: tasks/proxmox/copy_files.yml
      when: copy_files
      tags: ["copy_files"]

- name: Download and provision LXC templates/containers
  hosts: lxc
  gather_facts: false   # Because they don't exist yet
  become: true

  handlers:

    - import_tasks: handlers/proxmox.yml

  tasks:

    - name: Download and configure LXC containers
      import_tasks: tasks/proxmox/provision_lxcs.yml
      when: provision_lxcs
      tags: ["provision_lxcs"]
      delegate_to: proxmox1  # The hosts aren't provisioned yet, so no tasks should run on them. Delegate everything to proxmox but use lxc inventory.

- name: Download and configure base ubuntu template from cloud image
  hosts: proxmox1

  pre_tasks: *pre_tasks

  handlers:

    - import_tasks: handlers/proxmox.yml

  tasks:

    - name: Create Ubuntu VM Template from public cloud image
      import_role:
        name: proxmox/vm-template-from-ubuntu-cloud-image
      when: create_vm_template
      tags: ["create_vm_template"]

# Run this play with the docker host inventory, (load vm definition vars defined in each host_vars/host item), but delegate the tasks to proxmox
- name: Provision VM's on Proxmox Host
  hosts: docker_dev
  gather_facts: false   # Because they don't exist yet
  become: true

  handlers:

    - import_tasks: handlers/proxmox.yml

  tasks:

    - name: Provision VM's from template
      import_tasks: tasks/proxmox/provision_vms.yml
      when: provision_vms
      tags: ["provision_vms"]
      delegate_to: proxmox1  # The hosts aren't provisioned yet, so no tasks should run on them. Delegate everything to proxmox but use docker inventory.

    - name: Run Post Tasks
      import_tasks: tasks/proxmox/vm_post_tasks.yml
      when: provision_vms
      tags: ["provision_vms"]
