---
###################
### k3s cluster ###
###################

- name: Configure k3s cluster
  hosts: k3s
  become: true

  # Load in our default and vaulted vars
  vars_files: &vars_files   # Anchors to re-use the code later. No point duplicating code.
    - vars/vault.yml

  pre_tasks: &pre_tasks   # Anchors to re-use the code later. No point duplicating code.
    # Allow user to override defaults with their custom config file.
    # include_vars has a higher precedence than vars_files above, so import these files as overrides.
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/vars/config.yml"
      # Special tag 'always' -> https://docs.ansible.com/ansible/latest/user_guide/playbooks_tags.html#special-tags-always-and-never
      tags: ["always"]

    # Setup some required variables for the rest of the playbook
    - name: Instantiate user_dir
      set_fact:
        user_dir: "{{ lookup('env', 'HOME') }}"
      tags: ["always"]
    - name: Instantiate some extra vars from included vars
      set_fact:
        # docker_dir: "{{ user_dir }}/docker"
        git_dir: "{{ user_dir }}/git/personal"
        # secrets_dir: "{{ user_dir }}/docker/secrets"
      tags: ["always"]

    # This is to get the PUID and PGID variables to use later in multiple areas
    - name: Get user info or create a user if one doesn't exist
      import_tasks: tasks/linux/check_user.yml
      tags: ["always"]

  # Import handlers for all tasks
  handlers:
    - import_tasks: handlers/k3s.yml

  roles:
    - role: k3s/prereq
    - role: k3s/download
    - role: k3s/raspberrypi

- hosts: k3s_main
  become: yes

  vars_files:
    *vars_files

  pre_tasks:
    *pre_tasks

  roles:
    - role: k3s/master
  
  tasks:
    - name: install kubectl on localhost and Copy kube config
      import_tasks: tasks/k3s/kubectl_config.yml

- hosts: k3s_node
  become: yes

  vars_files:
    *vars_files

  pre_tasks:
    *pre_tasks

  roles:
    - role: k3s/node
