---
# import overrides
- hosts: wsl
  # Special tag "always" -> https://docs.ansible.com/ansible/latest/user_guide/playbooks_tags.html#special-tags-always-and-never
  tags: [ "always" ]
  gather_facts: false
  tasks:
  - name: Include playbook configuration.
    include_vars: "{{ item }}"
    with_fileglob:
      - "{{ playbook_dir }}/vars/config.yml"

####################
### WSL Personal ###
####################

- name: Setup Personal WSL
  hosts: wsl
  become: true

  pre_tasks:

    # This is to get the PUID and PGID variables to use later in multiple areas
    - name: Get user info or create a user if one doesn't exist
      import_tasks: tasks/linux/pre_tasks.yml
      tags: ["always"]

  roles:

    - andrewrothstein.kubectl
    - geerlingguy.helm
