---
###################
### k3s cluster ###
###################

- name: Configure k3s cluster
  hosts: k3s
  remote_user: "{{ vm.user | default(vm_defaults.user) }}"  # Login as user and become root
  become: true

  # Load in our default and vaulted vars
  vars_files: &vars_files   # Anchors to re-use the code later. No point duplicating code.
    - vars/vault.yml

  pre_tasks: &pre_tasks   # Anchors to re-use the code later. No point duplicating code.
    # Allow user to override defaults with their custom config file.
    # include_vars has a higher precedence than vars_files above, so import these files as overrides.
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/vars/config.yml"
      # Special tag 'always' -> https://docs.ansible.com/ansible/latest/user_guide/playbooks_tags.html#special-tags-always-and-never
      tags: ["always"]

    # Setup some required variables for the rest of the playbook
    - name: Instantiate user_dir
      set_fact:
        user_dir: "{{ lookup('env', 'HOME') }}"
      tags: ["always"]
    - name: Instantiate some extra vars from included vars
      set_fact:
        # docker_dir: "{{ user_dir }}/docker"
        git_dir: "{{ user_dir }}/git/personal"
        # secrets_dir: "{{ user_dir }}/docker/secrets"
      tags: ["always"]

    # This is to get the PUID and PGID variables to use later in multiple areas
    - name: Get user info or create a user if one doesn't exist
      import_tasks: tasks/linux/check_user.yml
      tags: ["always"]

  # Import handlers for all tasks
  handlers:
    - import_tasks: handlers/k3s.yml

  roles:
    - role: geerlingguy.docker
      vars:
        docker_install_compose: "false"   # I prefer to install the docker plugin version from apt repo (check install_os_packages task), until this role supports the plugin install -> https://github.com/geerlingguy/ansible-role-docker/issues/355
        # docker_compose_version: "v2.5.0"
        docker_users: ["{{ vm.user | default(vm_defaults.user) }}"]    # list of users who will be added to the docker group
      when: install_docker
      tags: ["install_docker"]

  tasks:

    - name: Install OS updates and required packages
      import_tasks: tasks/docker/install_os_packages.yml
      when: install_os_packages
      tags: ["install_os_packages"]

    - name: Configuring Hostname
      import_tasks: tasks/linux/configure_hostname.yml
      when: configure_hostname
      tags: ["configure_hostname"]

    - name: Pre-docker install tasks
      import_tasks: tasks/docker/pre_docker.yml
      tags: ["pre_docker"]

    - name: Configure gitlab registry and clone git repos
      import_tasks: tasks/docker/git.yml
      when: git
      tags: ["git"]

    - name: Updating docker-compose and related files
      import_tasks: tasks/docker/copy_files.yml
      when: copy_files
      tags: ["copy_files"]

    - name: Updating docker-compose and related files
      import_tasks: tasks/docker/update_compose.yml
      when: update_compose
      tags: ["update_compose"]

    - name: Setup container directories and copy files
      import_tasks: tasks/docker/setup_containers.yml
      when: setup_containers
      tags: ["setup_containers"]

    - name: Write logrotate files to host
      import_tasks: tasks/docker/logrotate.yml
      when: logrotate
      tags: ["logrotate"]

    - name: Setup NAS mounts
      import_tasks: tasks/docker/setup_nas_mounts.yml
      when: setup_nas_mounts
      tags: ["setup_nas_mounts"]

    - name: Setup Crons
      import_tasks: tasks/docker/setup_crons.yml
      when: setup_crons
      tags: ["setup_crons"]

    - name: Run Post tasks
      import_tasks: tasks/docker/run_post_tasks.yml
      when: run_post_tasks
      tags: ["run_post_tasks"]

    - name: Configure Home Assistant
      import_tasks: tasks/docker/hass_config.yml
      when: hass_config
      tags: ["hass_config"]
