---
# Todo:
  # Proxmox is installed from scratch on debian boxes (Checkout this role to configure a proxmox cluster on debian -> https://github.com/lae/ansible-role-proxmox)
  # Appropriate VM's are provisioned (k3s cluster, docker etc... whatever I'm currently running) -> https://www.youtube.com/watch?v=CbkEWcUZ7zM

# useful resources:
  # https://github.com/FuzzyMistborn/infra
  # https://github.com/ironicbadger/infra

### WARNING - Needs testing on a throwaway machine first -> https://github.com/lae/ansible-role-proxmox
# - name: Setup proxmox cluster on bare metal debian
#   hosts: proxmox_nodes
#   become: True
#   roles:
#     - role: lae.proxmox
#         - pve_group: all
#         - pve_reboot_on_kernel_update: true

- name: Configure Proxmox
  hosts: proxmox
  # Load in our default and vaulted vars
  vars_files: &vars_files   # Anchors to re-use the code later. No point duplicating code.
    - vars/vault.yml

  # Allow user to override defaults with their custom config file
  pre_tasks: &pre_tasks   # Anchors to re-use the code later. No point duplicating code.
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/vars/config.yml"
      # Special tag 'always' -> https://docs.ansible.com/ansible/latest/user_guide/playbooks_tags.html#special-tags-always-and-never
      tags: ["always"]

    - name: Instantiate some extra vars from included vars
      set_fact:
        user_dir: /home/{{ main_user }}
        docker_dir: /home/{{ main_user }}/docker
        git_dir: /home/{{ main_user }}/git/personal
        secrets_dir: /home/{{ main_user }}/docker/secrets
      tags: ["always"]

    # This is to get the PUID and PGID variables to use later in multiple areas
    - name: Get user info or create a user if one doesn't exist
      import_tasks: tasks/linux/check_user.yml
      tags: ["always"]

  roles:
    - ironicbadger.proxmox_nag_removal

  # Import handlers for all tasks
  handlers:
    - import_tasks: handlers/proxmox.yml

  tasks:
    - name: Ensure proxmox host is up, if not, send a Wake-on-LAN packet
      import_tasks: tasks/proxmox/host_start.yml
      tags: ["host_start"]

    - name: Install OS updates and required packages
      import_tasks: tasks/proxmox/install_os_packages.yml
      when: install_os_packages
      tags: ["install_os_packages"]

    - name: Copy files to proxmox host
      import_tasks: tasks/proxmox/copy_files.yml
      when: copy_files
      tags: ["copy_files"]

- name: Download and configure ubuntu template and Provision VM's on Proxmox Host
  hosts: proxmox1

  # Load in our default and vaulted vars
  vars_files:
    *vars_files

  # Allow user to override defaults with their custom config file
  pre_tasks:
    *pre_tasks

  # Import handlers for all tasks
  handlers:
    - import_tasks: handlers/proxmox.yml

  tasks:
    - name: Provision VM's
      import_tasks: tasks/proxmox/provision_vms.yml
      when: provision_vms
      tags: ["provision_vms"]

    - name: Start VM's
      import_tasks: tasks/proxmox/vm_start.yml
      when: vm_start
      tags: ["vm_start"]

    - name: Create Ubuntu VM Template from cloud image
      import_role:
        name: proxmox-template-from-ubuntu-cloud-image
      when: create_vm_template
      tags: ["create_vm_template"]

# LXC Containers - not done yet

# - name: Download and Configure LXC Containers on Proxmox Host
#   hosts: proxmox1

#   # Load in our default and vaulted vars
#   vars_files:
#     *vars_files

#   # Allow user to override defaults with their custom config file
#   pre_tasks:
#     *pre_tasks

#   # Import handlers for all tasks
#   handlers:
#     - import_tasks: handlers/proxmox.yml

#   roles:
#     - udelarinterior.proxmox_create_lxc
