---
# Todo:
  # Proxmox is installed from scratch on debian boxes (Checkout this role to configure a proxmox cluster on debian -> https://github.com/lae/ansible-role-proxmox)
  # Proxmox is setup/configured (Nag removal, telegraf, crons stuff like that)
    # add the following entries to /etc/sudoers file:
      # # Cmnd alias specification
      # Cmnd_Alias SMARTCTL = /usr/sbin/smartctl
      # # Give telegraf user access to exec scripts
      # telegraf  ALL=(ALL) NOPASSWD: SMARTCTL, /etc/telegraf/scripts/
      # Defaults!SMARTCTL !logfile, !syslog, !pam_session
  # The cloud image (ubuntu most likely) is downloaded and the template is configured
    # https://www.youtube.com/watch?v=shiIi38cJe4
    # https://docs.technotim.live/posts/cloud-init-cloud-image/#instructions
    # https://github.com/techno-tim/k3s-ansible
  # Appropriate VM's are provisioned (k3s cluster, docker etc... whatever I'm currently running) -> https://www.youtube.com/watch?v=CbkEWcUZ7zM
  # /etc/telegraf needs to be owned by telegraf:telegraf recursively

# Other useful resources:
  # https://github.com/FuzzyMistborn/infra
  # https://github.com/ironicbadger/infra

### WARNING - Needs testing on a throwaway machine first -> https://github.com/lae/ansible-role-proxmox
# - name: Setup proxmox cluster on bare metal debian
#   hosts: proxmox_nodes
#   become: True
#   roles:
#     - role: lae.proxmox
#         - pve_group: all
#         - pve_reboot_on_kernel_update: true

- name: Configure Proxmox
  hosts: proxmox
  # Load in our default and vaulted vars
  vars_files: &vars_files   # Anchors to re-use the code later. No point duplicating code.
    - vars/vault.yml

  # Allow user to override defaults with their custom config file
  pre_tasks: &pre_tasks   # Anchors to re-use the code later. No point duplicating code.
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/vars/config.yml"
      # Special tag 'always' -> https://docs.ansible.com/ansible/latest/user_guide/playbooks_tags.html#special-tags-always-and-never
      tags: ["always"]

    - name: Instantiate some extra vars from included vars
      set_fact:
        user_dir: /home/{{ main_user }}
        docker_dir: /home/{{ main_user }}/docker
        git_dir: /home/{{ main_user }}/git/personal
        secrets_dir: /home/{{ main_user }}/docker/secrets
      tags: ["always"]

    # This is to get the UID and GID variables to use later in multiple areas
    - name: Get user info or create a user if one doesn't exist
      import_tasks: tasks/linux/check_user.yml
      tags: ["always"]

  tasks:
    - name: debug test
      debug:
        msg: "whatevs"

- name: Download Ubuntu Cloud-Image and create a template from it
  hosts: proxmox1

  # Load in our default and vaulted vars
  vars_files:
    *vars_files

  # Allow user to override defaults with their custom config file
  pre_tasks:
    *pre_tasks

  tasks:
    - name: debug test
      debug:
        msg: "whatevs"

- name: Provision VM's on Proxmox Host
  hosts: proxmox1

  # Load in our default and vaulted vars
  vars_files:
    *vars_files

  # Allow user to override defaults with their custom config file
  pre_tasks:
    *pre_tasks

  # roles:
  #   - provision-docker-vm

  tasks:
    - name: debug test
      debug:
        msg: "whatevs"

    # This isn't ready yet...
    # - name: Create VM in Proxmox
    #   import_role:
    #     name: provision-docker-vm
    #   register: vm_provision
