---
# Proxmox #
## Personal Roles
# - name: create-proxmox-template-from-ubuntu-cloud-image
#   src: https://gitlab.com/sami-group/ansible-roles/create-proxmox-template-from-ubuntu-cloud-image.git
#   src: ssh://git@gitlab.com:sami-group/ansible-roles/create-proxmox-template-from-ubuntu-cloud-image.git
#   scm: git

## Others
- src: lae.proxmox  # Setup pve cluster on debian) - # Currently Unused
- src: udelarinterior.proxmox_create_kvm   # Provision the docker/k3s nodes - # Currently Unused
- src: udelarinterior.proxmox_create_lxc   # LXC containers provision
- src: ironicbadger.proxmox_nag_removal # Currently Unused
- src: rossmcdonald.telegraf  # Currently Unused -> https://github.com/rossmcdonald/telegraf

# Docker #
- src: arillso.logrotate
- src: geerlingguy.docker   # Currently Unused

# WSL #
# geerlingguy.docker as above
- src: geerlingguy.ntp  # Currently Unused - This is also for proxmox above
