---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: plex
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`plex.shaklab.com`)
      kind: Rule
      middlewares:
        - name: middlewares-chain-no-auth
      services:
        - name: plex
          port: 32400
  tls:
    secretName: shaklab-com-tls-certs
