---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config
  namespace: default
  # labels:
  #   app.kubernetes.io/instance: plex
  #   app.kubernetes.io/name: plex
spec:
  storageClassName: local-path
  # volumeName: pv-plex-config
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: plex-nfs-movies
#   namespace: default
# spec:
#   storageClassName: ""
#   volumeName: pv-nfs-movies
#   accessModes:
#     - ReadWriteMany
#   volumeMode: Filesystem
#   resources:
#     requests:
#       storage: 1T
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: plex-nfs-tv
#   namespace: default
# spec:
#   storageClassName: ""
#   volumeName: pv-nfs-tv
#   accessModes:
#     - ReadWriteMany
#   volumeMode: Filesystem
#   resources:
#     requests:
#       storage: 1T
