---
#######################################
### THIS FILE IS MANAGED BY ANSIBLE ###
###    PLEASE MAKE CHANGES THERE    ###
#######################################

version: "3.7"

########################### EXTENSION FIELDS

# To use this put this block in your service: "<<: *logging"
x-logging: &logging
  logging:
    driver: loki
    options:
      loki-url: "http://${SERVER_IP}:${LOKI_PORT}/loki/api/v1/push"

########################### SERVICES

services:
  # Eufy security websocket addon - for homeassistant
  # https://hub.docker.com/r/bropat/eufy-security-ws
  eufy-security-ws:
    container_name: eufy-security-ws
    image: "bropat/eufy-security-ws"
    init: true
    restart: always
    ports:
      - "${EUFY_SECURITY_WS_PORT}:3000/tcp"   # Websocket app port used for home assistant integration
    depends_on:
      - homeassistant
    environment:
      USERNAME: ${EUFY_ADDON_EMAIL}
      PASSWORD: ${EUFY_ADDON_PASSWORD}
    # volumes:
    #   - "${DOCKERDIR}/hass-configurator:/config"
    #   - "${DOCKERDIR}/homeassistant:/hass-config"
    # user: "${PUID}:${PGID}"
    <<: *logging
