---
#######################################
### THIS FILE IS MANAGED BY ANSIBLE ###
###    PLEASE MAKE CHANGES THERE    ###
#######################################

version: "3.7"

########################### EXTENSION FIELDS

# Default TZ, uid and pid
# To use this put this block in your service: "<<: *default-tz-uid-gid"
x-environment: &default-tz-uid-gid
  TZ: $TZ
  PUID: $PUID
  PGID: $PGID

# To use this put this block in your service: "<<: *logging"
x-logging: &logging
  logging:
    driver: loki
    options:
      loki-url: "http://${SERVER_IP}:${LOKI_PORT}/loki/api/v1/push"

########################### SERVICES

services:
  # Home Assistant Core - Home Automation
  # https://hub.docker.com/r/homeassistant/home-assistant/
  # We do traefik via file rule, because of host networking
  # Also install the following from HACS:
  # https://github.com/thomasloven/lovelace-slider-entity-row
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:stable
    init: true
    restart: always
    healthcheck:
      test: curl --connect-timeout 10 --silent -f http://localhost:8123/ || exit 1
      interval: 45s
      timeout: 10s
      retries: 3
    network_mode: host
    depends_on:
      influxdb:
        condition: service_healthy
      mariadb:    # MariaDB is optional (only if you would like to use a different database for HA).
        condition: service_healthy
      mqtt:     # mqtt is optional (only if you want to add Zigbee devices and have a zigbee sniffer attached).
        condition: service_started
      zigbee2mqtt:  # zigbee2mqtt is optional (only if you want to add Zigbee devices and have a zigbee sniffer attached).
        condition: service_started
    ports:
      - "${HOME_ASSISTANT_PORT}:8123"
    devices:    # If you have any zigbee usb devices, mount them here
      - ${ZIGBEE_ADAPTER_TTY}:/dev/ttyACM0    # Use this for conbee II
    privileged: true
    volumes:
      - ${DOCKERDIR}/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      #- /media/ssd/motioneye:/media/motioneye
    environment:
      <<: *default-tz-uid-gid
      # MYSQL_USER: ${MARIADB_USER}
      # MYSQL_PASSWORD: ${MARIADB_PASSWORD}
      # MYSQL_DATABASE: ${MARIADB_DATABASE}
      # MYSQL_HOST: ${SERVER_IP}
    labels:
      ## Exclude From Watchtower
      - "com.centurylinklabs.watchtower.enable=false"
      ## Traefik ##
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.hass-rtr.entrypoints=https"
      - "traefik.http.routers.hass-rtr.rule=Host(`hass.${DOMAINNAME}`)"
      ## Middlewares
      - "traefik.http.routers.hass-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.hass-rtr.service=hass-svc"
      - "traefik.http.services.hass-svc.loadbalancer.server.port=8123"
    <<: *logging
