---
#######################################
### THIS FILE IS MANAGED BY ANSIBLE ###
###    PLEASE MAKE CHANGES THERE    ###
#######################################

version: "3.7"

########################### SERVICES

services:
  # Mosquitto - MQTT Broker
  # To set this up, ensure the files from the DOCKERDIR folder are transferred to the docker VM
  # i.e. mosquitto.conf, passwd, mosquitto.log files and set permissions to 775 user:docker
  # Then run the following to setup a user/password to publish and subscribe to the queues:
  # dexec mqtt /bin/sh   # To enter the container
  # mosquitto_passwd -b /mosquitto/config/passwd <username> <passwd>  # Generate the passwd file
  # You can test this from Home Assistant with the following commands:
  # mosquitto_sub -h x.x.x.x -p 1883 -u username -P password -v -t "home-assistant/#"
  # mosquitto_pub -h x.x.x.x -p 1883 -u username -P password -t home-assistant/test -m "test"
  # https://hub.docker.com/_/eclipse-mosquitto
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:latest
    restart: always
    healthcheck:
      test: nc -z localhost 1883
      interval: 60s
      timeout: 3s
      retries: 3
    user: ${PUID}:${PGID}
    security_opt:
      - no-new-privileges:true
    ports:
      # If you change these, please reflect the "listener" in the config file
      - "${MOSQUITTO_HTTP_PORT}:1883"   # http
      - "${MOSQUITTO_WS_PORT}:9001"     # websockets
      # - "${MOSQUITTO_HTTPS_PORT}:8883"  # https
    volumes:
      - ${DOCKERDIR}/mqtt/config:/mosquitto/config
      - ${DOCKERDIR}/mqtt/log:/mosquitto/log
      - ${DOCKERDIR}/mqtt/data:/mosquitto/data
    environment:
      TZ: ${TZ}
