---
#######################################
### THIS FILE IS MANAGED BY ANSIBLE ###
###    PLEASE MAKE CHANGES THERE    ###
#######################################

version: "3.7"

########################### EXTENSION FIELDS

# To use this put this block in your service: "<<: *logging"
x-logging: &logging
  logging:
    driver: loki
    options:
      loki-url: "http://${SERVER_IP}:${LOKI_PORT}/loki/api/v1/push"

########################### NETWORKS

networks:
  traefik_proxy:
    name: traefik_proxy
    external: true

########################### SERVICES

services:
  # Display zigbee devices and the status of each of them.
  # https://hub.docker.com/r/carldebilly/zigbee2mqttassistant
  # https://github.com/yllibed/Zigbee2MqttAssistant
  zigbee2mqttassistant:
    container_name: zigbee2mqttassistant
    image: carldebilly/zigbee2mqttassistant
    init: true
    restart: unless-stopped
    depends_on:
      zigbee2mqtt:
        condition: service_started
    ports:
      - ${ZIGBEE2MQTTASSISTANT_PORT}:80
    networks:
      - traefik_proxy
    environment:
      - Z2MA_SETTINGS__MQTTSERVER=${SERVER_IP}    # IP/Hostname of the mqtt container
      - Z2MA_SETTINGS__MQTTUSERNAME=${MQTT_USER}
      - Z2MA_SETTINGS__MQTTPASSWORD=${MQTT_PASS}
      - TZ=${TZ}
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.zigbee2mqttassistant-rtr.entrypoints=https"
      - "traefik.http.routers.zigbee2mqttassistant-rtr.rule=Host(`zigbee-assistant.${DOMAINNAME}`)"
      ## Middlewares
      - "traefik.http.routers.zigbee2mqttassistant-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.zigbee2mqttassistant-rtr.service=zigbee2mqttassistant-svc"
      - "traefik.http.services.zigbee2mqttassistant-svc.loadbalancer.server.port=80"
    <<: *logging
