---
#######################################
### THIS FILE IS MANAGED BY ANSIBLE ###
###    PLEASE MAKE CHANGES THERE    ###
#######################################

version: "3.7"

########################### EXTENSION FIELDS

# Default TZ, uid and pid
# To use this put this block in your service: "<<: *default-tz-uid-gid"
x-environment: &default-tz-uid-gid
  TZ: $TZ
  PUID: $PUID
  PGID: $PGID

# To use this put this block in your service: "<<: *logging"
x-logging: &logging
  logging:
    driver: loki
    options:
      loki-url: "http://${SERVER_IP}:${LOKI_PORT}/loki/api/v1/push"

########################### NETWORKS

networks:
  traefik_proxy:
    name: traefik_proxy
    external: true

########################### SERVICES

services:
  # VS-Code Server
  # https://hub.docker.com/r/linuxserver/code-server
  vscode:
    container_name: vscode
    image: lscr.io/linuxserver/code-server
    init: true
    restart: unless-stopped
    healthcheck:
      test: curl -sI http://localhost:8443
      interval: 60s
      timeout: 3s
      retries: 3
    networks:
      - traefik_proxy
    ports:
      - ${VSCODE_PORT}:8443
    volumes:
      - /path/to/appdata/config:/config
    environment:
      <<: *default-tz-uid-gid
      # PASSWORD: password                  # optional
      # HASHED_PASSWORD:                    # optional
      # SUDO_PASSWORD: password             # optional
      # SUDO_PASSWORD_HASH:                 # optional
      PROXY_DOMAIN: code.${DOMAINNAME}      # optional
      DEFAULT_WORKSPACE: /config/workspace  # optional
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.vscode-rtr.entrypoints=https"
      - "traefik.http.routers.vscode-rtr.rule=Host(`code.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.vscode-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.vscode-rtr.service=vscode-svc"
      - "traefik.http.services.vscode-svc.loadbalancer.server.port=8443"
    <<: *logging
