---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homelab-dev-container-all
  namespace: kube-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: homelab-dev-container
  target:
    name: homelab-dev-container-all
  dataFrom:
    - find:
        name:
          regexp: .*
