---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: nginx-noauth
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`nginx.shaklab.com`, `shaklab.com`, `docs.shaklab.com`, `www.shaklab.com`, `home.shaklab.com`)
      kind: Rule
      middlewares:
        - name: middlewares-chain-no-auth
      services:
        - name: nginx
          port: 80
  tls:
    secretName: shaklab-com-tls-certs
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: nginx-oauth
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`personal-docs.shaklab.com`)
      kind: Rule
      middlewares:
        - name: middlewares-chain-oauth
      services:
        - name: nginx
          port: 80
  tls:
    secretName: shaklab-com-tls-certs
