---
nas_dir: "/mnt/pve/NAS"
img_dir: "{{ nas_dir }}/template/iso"
truenas_iso_url: https://download.truenas.com/TrueNAS-SCALE-Bluefin/22.12.3.1/TrueNAS-SCALE-22.12.3.1.iso

truenas_vm:
  name: TrueNAS
  id: 100
  storage: nvme
  memory: 8192 # ram for each VM in MBz

# Find this out with `lsblk -o +MODEL,SERIAL`. Then find the device in `/dev/disk/by-id/`
passthrough_disks:
  1: nvme-CT1000P3SSD8_2307E6AD2A71
  2: nvme-CT1000P3SSD8_2308E6B1C1D6
  3: ata-WDC_WD80EFZX-68UW8N0_VK0JMK8Y
  4: ata-WDC_WD80EFZX-68UW8N0_VK0LU2WY
