---
- name: Install/configure Helm/kubectl on main nodes
  hosts: k3s_master
  become: true

  roles:

    - andrewrothstein.kubectl
    - geerlingguy.helm  # Install helm on k3sm nodes to deploy charts in ansible

- name: Custom plays on main..main node
  hosts: k3s_master
  become: false

  tasks:

    - name: Setup system dependencies
      ansible.builtin.import_tasks: ../tasks/k3s/system_dependencies.yml
      become: true

    - name: Setup user dependencies
      ansible.builtin.import_tasks: ../tasks/k3s/user_dependencies.yml

    # - name: deploy k8s manifests
    #   import_role:
    #     name: geerlingguy.k8s_manifests # Deploys everything inside file - `group_vars/all.yml` lines starting - `k8s_*`
    #   tags: ['nfs', 'k8s_manifests']

    # - name: Deploy Helm Charts
    #   import_tasks: ../tasks/k3s/deploy_helm_charts.yml
