---
# ----------------------------------- #
# Pre-tasks run before anything else! #
# ----------------------------------- #
- name: Pre-all
  hosts: nuc
  gather_facts: false
  tasks:
    - name: Pre-all
      ansible.builtin.import_tasks: ../tasks/pre-all.yml

- name: Configure Nuc
  hosts: nuc

  pre_tasks:

    # This is to get the PUID and PGID variables to use later in multiple areas
    - name: Get user info or create a user if one doesn't exist
      ansible.builtin.import_tasks: ../tasks/linux/pre_tasks.yml
      tags: ["always"]

  roles:

    - xanmanning.k3s
    - andrewrothstein.kubectl
    - geerlingguy.helm  # Install helm on k3sm nodes to deploy charts in ansible
