---
- name: Setup proxmox on bare metal debian machines
  hosts: pve01
  become: True

  roles:

    - role: lae.proxmox
      vars:
        - pve_group: all
        - pve_cluster_enabled: yes
        - pve_reboot_on_kernel_update: true
