---
- name: Check conectivity
  block:
    - name: 'Check conectivity with hypervisor'
      wait_for:
        host: "{{ proxmox_host }}"
        port: "{{ proxmox_port }}"
        delay: 0
        timeout: 10
  rescue:
    - name: WOL to hypervisor
      wakeonlan:
        mac: "{{ proxmox_mac }}"
        broadcast: "{{ proxmox_broadcast }}"
    - name: 'Check conectivity with hypervisor'
      wait_for:
        host: "{{ proxmox_host }}"
        port: "{{ proxmox_port }}"
    - name: 'Sleep a bit more'
      wait_for:
        delay: 15
        timeout: 0
  delegate_to: localhost
  connection: local
