---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: middlewares-authelia
spec:
  forwardAuth:
    address: "http://authelia:9091/api/verify?rd=https://auth.{{ domain_name }}"
    trustForwardHeader: true
    authResponseHeaders:
      - "Remote-User"
      - "Remote-Groups"
      - "Remote-Name"
      - "Remote-Email"
