---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: middlewares-chain-no-auth
spec:
  chain:
    middlewares:
      - name: middlewares-rate-limit
      - name: middlewares-https-redirectscheme
      - name: middlewares-secure-headers
      - name: middlewares-compress
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: middlewares-chain-basic-auth
spec:
  chain:
    middlewares:
      - name: middlewares-rate-limit
      - name: middlewares-https-redirectscheme
      - name: middlewares-secure-headers
      - name: middlewares-basic-auth
      - name: middlewares-compress
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: middlewares-chain-oauth
spec:
  chain:
    middlewares:
      - name: middlewares-rate-limit
      - name: middlewares-https-redirectscheme
      - name: middlewares-secure-headers
      - name: middlewares-oauth
      - name: middlewares-compress
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: middlewares-chain-oauth-no-ratelimit
spec:
  chain:
    middlewares:
      - name: middlewares-https-redirectscheme
      - name: middlewares-secure-headers
      - name: middlewares-oauth
      - name: middlewares-compress
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: middlewares-chain-authelia
spec:
  chain:
    middlewares:
      - name: middlewares-rate-limit
      - name: middlewares-https-redirectscheme
      - name: middlewares-secure-headers
      - name: middlewares-authelia
      - name: middlewares-compress
