---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: volsync
  namespace: kube-system
spec:
  interval: 1h
  chart:
    spec:
      chart: volsync
      version: 0.7.1
      sourceRef:
        kind: HelmRepository
        name: backube
        namespace: flux-system
      interval: 1h
  values:
    manageCRDs: true
    metrics:
      disableAuth: true
