---
# http:
#   routers:
#     traefik-k3s-router:
#       rule: "Host(`nginx.shaklab.com`)"
#       service: traefik-k3s-service
#       middlewares:
#         - chain-oauth
#   services:
#     traefik-k3s-service:
#       loadBalancer:
#         servers:
#           - url: "http://10.10.0.81:80"

# tcp:
#   routers:
#     shaklab-rtr:
#       rule: "HostSNI(`nginx.shaklab.com`) || HostSNI(`shaklab.com`)"
#       service: shaklab-svc
#       tls:
#         passthrough: true
#   services:
#     shaklab-svc:
#       loadBalancer:
#         servers:
#           - address: 10.10.0.81
#             port: 80
