#######################################
### THIS FILE IS MANAGED BY ANSIBLE ###
###    PLEASE MAKE CHANGES THERE    ###
#######################################

http:
  routers:
    transmission-vpn-rtr:
      rule: "Host(`transmission.{{ domain_name }}`, `torrent.{{ domain_name }}`)"
      entryPoints:
        - https
      middlewares:
        - chain-oauth
      service: transmission-vpn-svc
  services:
    transmission-vpn-svc:
      loadBalancer:
        servers:
          - url: "http://{{ nas_ip }}:{{ transmission_port }}"
