---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: homelab-dev-container
  namespace: kube-system
spec:
  provider:
    doppler:
      project: homelab
      config: dev_container
      auth:
        secretRef:
          dopplerToken:
            name: doppler-token-auth-api
            key: dopplerToken
            namespace: kube-system
