---
# Playbook run tasks default actions:
install_os_packages: true
configure_hostname: true
# Setting default to false (this can be changed from time to time), run `make update-compose` whenever it needs updating, don't want it updating with the rest of the playbook accidentally.
update_compose: true
logrotate: true
setup_containers: true
setup_nas_mounts: true
setup_crons: true
test_task: false    # Do not change this. If you want to run the test task, use `make test` instead.
run_post_tasks: true
hass_config: true
install_docker: true
git: true

# Docker .env file defaults
# Ports
bazarr_port: '6767'
jackett_port: '9117'
grafana_port: '3000'
influxdb_port: '8086'
plex_port: '32400'
plex_web_tools_port: '33400'
jellyfin_port: '8096'
portainer_port: '9000'
radarr_port: '7878'
sonarr_port: '8989'
prowlarr_port: '9696'
tautulli_port: '8181'
qbittorrent_port: '8787'
transmission_port: '9091'
mosquitto_http_port: '1883'
mosquitto_ws_port: '9001'
mosquitto_https_port: '8883'
loki_port: '3100'
moviematch_port: '8001'
vscode_port: '8446'
overseerr_port: '5055'
homer_port: '8456'
mariadb_port: '3306'
phpmyadmin_port: '8000'
authelia_port: '9092'
tdarr:
  webui_port: '8265'
  server_port: '8266'
  node_port: '8267'
photoprism_port: '2342'
eufy_security_ws_port: '3007'
zigbee2mqtt_port: '9442'
zigbee2mqttassistant_port: '8881'
redis_port: '6379'
rediscommander_port: '8081'
hass_configurator_port: '3218'
mkdocs_port: '8554'
node_api_port: '8555'

# Others
name_servers: '1.1.1.1,1.0.0.1'
watchtower_interval: 15000

# Traefik rules (not docker)
home_assistant_port: '8123'
oauth_port: '4181'
pfsense_port: '50000'
syncthing_port: '8384'
proxmox_port: '8006'

# Required directories and files to be created before docker templates/files can be copied
required_items:
  folders:
    - /var/log/traefik
    - /var/log/nginx
    - "{{ docker_dir }}/secrets"
    - "{{ docker_dir }}/scripts"
    - "{{ docker_dir }}/mqtt/log"
    - "{{ docker_dir }}/mqtt/config"
    - "{{ docker_dir }}/traefik/acme"
    - "{{ docker_dir }}/traefik/rules"
    - "{{ docker_dir }}/nginx/conf.d"
    - "{{ docker_dir }}/promtail/etc"
    - "{{ docker_dir }}/homeassistant"
  no_recurse_folders:
    - "{{ docker_dir }}/shared/plexms"
    - "{{ docker_dir }}/shared/radarr/MediaCover"
    - "{{ docker_dir }}/shared/sonarr/MediaCover"
  files:
    - /var/log/traefik/traefik.log
    - /var/log/nginx/{{ domain_name }}.access.log
    - /var/log/nginx/{{ domain_name }}.error.log
    - /var/log/nginx/nginx-error.log
    - "{{ docker_dir }}/nginx/nginx.conf"
    - "{{ docker_dir }}/mqtt/log/mosquitto.log"
    - "{{ docker_dir }}/mqtt/config/passwd"
    - "{{ docker_dir }}/traefik/acme/acme.json"
    - "{{ docker_dir }}/scripts/mail.txt"
    - "{{ docker_dir }}/homeassistant/home-assistant.log"   # Required for hacs to install.. Check it's install script code..

##############################################
######### Currently Unused Variables #########
##############################################

##### PORTS

# organizer_port: '9001'
# zoneminder_http_port: ''
# zoneminder_https_port: ''
# apcupsd_port: ''
# emby_port: ''
# guacamole_port: ''
# ha_dockermon_port: ''
# heimdall_port: ''
# ipvanish_proxy_port: ''
# ipvanish_remote_server: ''
# jdownloader_port: ''
# lidarr_port: ''
# nzbhydra_port: ''
# sabnzbd_port: ''
# sabnzbd_port: ''

##### PLEX

# Plex libraries section id. Remember to change the numbers below to reflect your library. Add more as needed.
# ALWAYS DO A DRY RUN TO VERIFY BEFORE SYNCING (I'm commenting them out because they may cause issues for you deploying)
# SYN_PLEX_HOLLYWOOD=1
# NUC_PLEX_HOLLYWOOD=2
# SYN_PLEX_TVSHOWS=2
# NUC_PLEX_TVSHOWS=16
