---
vm_ip_address: "{{ vm_network }}20"  # Required

vm:
  # name: docker   # Default is ansible magic var `inventory_hostname_short` if omitted
  ipconfig:
    ipconfig0: "ip={{ vm_ip_address }}/{{ vm_netmask }},gw={{ vm_gateway }}"
  id: 201   # Required
  hdd_size: "50G"
  cores: 2
  memory: 8000
  template: "UbuntuCloud-jammy-22.04"   # Specify a template
  storage: "local"
