---
vm_ip_address: "{{ vm_network }}22"  # Required
docker_ip: "{{ vm_ip_address }}"

vm:
  # name: docker-dev    # Default is ansible magic var `inventory_hostname_short` if omitted
  ipconfig:
    ipconfig0: "ip={{ vm_ip_address }}/{{ vm_netmask }},gw={{ vm_gateway }}"
  id: 210   # Required
  hdd_size: "30G"
  cores: 4
  memory: 12000
  # template: "UbuntuCloud-jammy"   # Specify a template
