---
vm_ip_address: "{{ vm_network }}34"  # Required

vm:
  # name: k3s-vm1   # Default is ansible magic var `inventory_hostname_short` if omitted
  ipconfig:
    ipconfig0: "ip={{ vm_ip_address }}/{{ vm_netmask }},gw={{ vm_gateway }}"
  id: 116   # Required
  hdd_size: "20G"
  cores: 2
  memory: 8000
  template: "DebianCloud-bullseye-11"   # Specify a template
  storage: "local"
