---
##################
### K3s Node 3 ###
##################

vm_ip_address: "{{ vm_network }}37"  # Required

vm:
  # name: k3sn3    # Default is ansible magic var `inventory_hostname_short` if omitted
  ipconfig:
    ipconfig0: "ip={{ vm_ip_address }}/{{ vm_netmask }},gw={{ vm_gateway }}"
  id: 207   # Required
  hdd_size: "12G"
  cores: 2
  memory: 2048
  # template: "UbuntuCloud-jammy"   # Specify a template
