---
vm_ip_address: "{{ vm_network }}21"  # Required

vm:
  # name: docker   # Default is ansible magic var `inventory_hostname_short` if omitted
  ipconfig:
    ipconfig0: "ip={{ vm_ip_address }}/{{ vm_netmask }},gw={{ vm_gateway }}"
  id: 102   # Required
  hdd_size: "20G"
  cores: 2
  memory: 4000
  template: "{{ template_vm_debian_defaults.name }}"   # Specify a template
