---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: discord-bot-alert
  namespace: kube-system
spec:
  eventSeverity: info
  eventSources:
  - kind: GitRepository
    name: '*'
  - kind: Kustomization
    name: '*'
  - kind: ImagePolicy
    name: '*'
  - kind: HelmRepository
    name: '*'
  - kind: HelmRelease
    name: '*'
  providerRef:
    name: discord
