---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: doppler-dev
spec:
  provider:
    doppler:
      auth:
        secretRef:
          dopplerToken:
            name: doppler-token-dev
            key: dopplerToken
