---
# https://docs.ansible.com/ansible/latest/collections/kubernetes/core/helm_module.html
- name: Install helm repositories
  kubernetes.core.helm_repository:
    name: "{{ item.name }}"
    repo_url: "{{ item.url }}"
  with_items:
    - name: bitnami
      url: https://charts.bitnami.com/bitnami
    - name: k8s-at-home
      url: https://k8s-at-home.com/charts/
    - name: grafana
      url: https://grafana.github.io/helm-charts

### These charts install, but need to figure out how to input values with_items for LoadBalancer type service ###

- name: Install Helm Charts
  kubernetes.core.helm:
    name: "{{ item.name }}"
    chart_ref: "{{ item.chart_ref }}"
    release_namespace: "{{ item.release_namespace }}"    # Will be web/monitoring etc later.
    # create_namespace: true
    # values: {"*.service.type": "LoadBalancer"}
    ### NOT WORKING YET ###
    values: |
      {% set item_name = item.name %}
      {% macro helm_values(name) -%}
        lookup('template', 'k3s/values/{{ item_name }}.yml') | from_yaml
      {%- endmacro %}
      {{ helm_values( item_name ) | default(omit) }}
    with_items:
      - name: nginx
        chart_ref: bitnami/nginx
        release_namespace: default
      - name: grafana
        chart_ref: bitnami/grafana
        release_namespace: default
      - name: grafana-loki
        chart_ref: bitnami/grafana-loki
        release_namespace: default

# - name: Install Helm Charts
#   kubernetes.core.helm:
#     name: grafana
#     chart_ref: bitnami/grafana
#     release_namespace: default
#     create_namespace: true
#     values:
#       replicas: 2
