---
- name: copy kubectl config from k3sm1 server
  fetch:
    src: "{{ user_dir }}/.kube/config"
    dest: "{{ user_dir }}/.kube/config"
    flat: yes
  when: ansible_host == hostvars[groups['k3s_main'][0]]['ansible_host'] | default(groups['k3s_main'][0])
