#######################################
### THIS FILE IS MANAGED BY ANSIBLE ###
###    PLEASE MAKE CHANGES THERE    ###
#######################################

version: '3.7'
services:

  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    restart: unless-stopped
    networks:
      traefik_proxy:
        ipv4_address: 192.168.90.172 # You can specify a static IP - I also created a non-proxied DNS record like 'bazarr-dc.domain.com' pointing to this IP so i don't need to reference this all the time.
    security_opt:
      - no-new-privileges:true
    # ports:
    #   - ${BAZARR_PORT}:6767
    volumes:
      - ${DOCKERDIR}/bazarr:/config
      - ${USERDIR}/mount/video/movies:/movies
      - ${USERDIR}/mount/video/tv:/tv
    environment:
      UID: ${UID}
      GID: ${GID}
      TZ: ${TZ}
    labels:
      - "traefik.enable=true"
      ## HTTP Routers Auth Bypass
      - "traefik.http.routers.bazarr-rtr-bypass.entrypoints=https"
      - "traefik.http.routers.bazarr-rtr-bypass.rule=Host(`bazarr.$DOMAINNAME`) && (Headers(`X-Api-Key`, `$BAZARR_API_KEY`) || Query(`apikey`, `$BAZARR_API_KEY`))"
      - "traefik.http.routers.bazarr-rtr-bypass.priority=100"
      ## HTTP Routers Auth
      - "traefik.http.routers.bazarr-rtr.entrypoints=https"
      - "traefik.http.routers.bazarr-rtr.rule=Host(`bazarr.$DOMAINNAME`)"
      - "traefik.http.routers.bazarr-rtr.priority=99"
      ## Middlewares
      - "traefik.http.routers.bazarr-rtr-bypass.middlewares=chain-no-auth@file"
      - "traefik.http.routers.bazarr-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.bazarr-rtr.service=bazarr-svc"
      - "traefik.http.routers.bazarr-rtr-bypass.service=bazarr-svc"
      - "traefik.http.services.bazarr-svc.loadbalancer.server.port=6767"
