---
#######################################
### THIS FILE IS MANAGED BY ANSIBLE ###
###    PLEASE MAKE CHANGES THERE    ###
#######################################

version: "3.7"
services:

  # This container registers (non-interactively) the gitlab runner
  # https://hub.docker.com/r/gitlab/gitlab-runner
  gitlab-register:
    container_name: gitlab-register
    image: gitlab/gitlab-runner:alpine
    command:
      - register
    volumes:
      - ${DOCKERDIR}/gitlab-runner:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro    # Syncronize time of container with the host system
    environment:
      # You can pass any cli arg and value in as environment variables, e.g. these env vars are args for the `gitlab-runner register` command.
      # https://docs.gitlab.com/runner/commands/#using-environment-variables
      TZ: $TZ
      REGISTER_NON_INTERACTIVE: true                # Run registration unattended
      CI_SERVER_URL: https://gitlab.com/            # Runner URL
      REGISTRATION_TOKEN: ${GITLAB_RUNNER_TOKEN}    # Runner's registration token
      RUNNER_EXECUTOR: docker                       # Select executor, eg. shell, docker, etc.
      RUNNER_NAME: Gitlab Runner Docker             # Runner name
      # RUNNER_TAG_LIST: docker                       # Tag list
      REGISTER_LOCKED: false                        # Lock Runner for current project
      DOCKER_IMAGE: docker:stable                   # Docker image to be used
      DOCKER_PRIVILEGED: true                       # Give extended privileges to container
      DOCKER_HOST: tcp://localhost:2375             # Docker daemon address
      DOCKER_TLS_CERTDIR: ""                        # HOTFIX?
      DOCKER_VOLUMES: '/var/run/docker.sock:/var/run/docker.sock'
      # DOCKER_EXTRA_HOSTS: gitlab:${GITLAB_IP}       # Add a custom host-to-IP mapping
