#######################################
### THIS FILE IS MANAGED BY ANSIBLE ###
###    PLEASE MAKE CHANGES THERE    ###
#######################################

version: '3.7'
services:

  loki:
    container_name: loki
    image: grafana/loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    volumes:
      # - ${DOCKERDIR}/loki/config/loki-config.yaml:/etc/loki/loki-config.yaml
      - ${DOCKERDIR}/loki/data:/data/loki
    # command: -config.file=/etc/loki/loki-config.yaml
    # logging:
    #   driver: loki
    #   options:
    #     loki-url: "http://localhost:3100/loki/api/v1/push"
