#######################################
### THIS FILE IS MANAGED BY ANSIBLE ###
###    PLEASE MAKE CHANGES THERE    ###
#######################################

version: "3.7"
services:

  # MariaDB – Database Server for your Apps
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: unless-stopped
    hostname: mariadb
    ports:
      - 3306:3306
    volumes:
      - ${USERDIR}/docker/mariadb/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=test
      - UID=${UID}
      - GID=${GID}
      - TZ=${TZ}
