#######################################
### THIS FILE IS MANAGED BY ANSIBLE ###
###    PLEASE MAKE CHANGES THERE    ###
#######################################

version: "3.7"
networks:
  default:
    driver: bridge
  t2_proxy:
    external:
      name: t2_proxy
