#######################################
### THIS FILE IS MANAGED BY ANSIBLE ###
###    PLEASE MAKE CHANGES THERE    ###
#######################################

version: '3.7'
services:

  ### OLD WAY - I BUILD A CUSTOM IMAGE NOW ###
  # Nginx for my website
  # https://hub.docker.com/_/nginx/
  nginx:
    container_name: nginx
    image: nginx
    restart: unless-stopped
    healthcheck:
      test: curl -sI http://localhost:80
      interval: 60s
      timeout: 3s
      retries: 3
    networks:
      traefik_proxy:
        ipv4_address: 192.168.90.136 # You can specify a static IP
    volumes:
    - "${DOCKERDIR}/nginx/conf.d:/etc/nginx/conf.d"
    - "${DOCKERDIR}/nginx/nginx.conf:/etc/nginx/nginx.conf"
    - "${DOCKERDIR}/nginx/html:/usr/share/nginx/html"         # Main domain website files
    - "${DOCKERDIR}/nginx/docs:/usr/share/nginx/docs"         # mkdocs files
    - "/var/log/nginx:/var/log/nginx"
    # - ./templates:/etc/nginx/templates
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.website-rtr.entrypoints=https"
      - "traefik.http.routers.website-rtr.rule=Host(`$DOMAINNAME`, `www.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.website-rtr.middlewares=chain-no-auth@file"
    environment:
      TZ: $TZ
    <<: *logging