#######################################
### THIS FILE IS MANAGED BY ANSIBLE ###
###    PLEASE MAKE CHANGES THERE    ###
#######################################

version: '3.7'
services:

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: always
    network_mode: service:transmission-vpn
    depends_on:
      - transmission-vpn
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${DOCKERDIR}/qbittorrent:/config
      - ${USERDIR}/mount/downloads:/downloads
    environment:
      UID: ${UID}
      GID: ${GID}
      TZ: ${TZ}
      # UMASK: 002
      WEBUI_PORT: 8168
    # ports:
    #   - 6881:6881
    #   - 6881:6881/udp
    #   - 8168:8168
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.qbittorrent-rtr.entrypoints=https"
      - "traefik.http.routers.qbittorrent-rtr.rule=Host(`qbit.$DOMAINNAME`, `qbittorrent.$DOMAINNAME`)"
      # - "traefik.http.routers.qbittorrent-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.qbittorrent-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.qbittorrent-rtr.service=qbittorrent-svc"
      - "traefik.http.services.qbittorrent-svc.loadbalancer.server.port=8168"
