#######################################
### THIS FILE IS MANAGED BY ANSIBLE ###
###    PLEASE MAKE CHANGES THERE    ###
#######################################

version: '3.7'
services:

  unifi:
    container_name: unifi
    image: linuxserver/unifi-controller
    restart: unless-stopped
    networks:
      traefik_proxy:
        ipv4_address: 192.168.90.153 # You can specify a static IP
    security_opt:
      - no-new-privileges:true
    ports:
      - 3478:3478/udp # Required - Unifi STUN port
      - 10001:10001/udp # Required - Device discovery
      - 8080:8080 # Required - Device and controller communication
      - 8443:8443 # Required - Web GUI/API port
      # - 1900:1900/udp # optional - Required for `Make controller discoverable on L2 network` option - Currently clashes with plex DLNA
      - 8843:8843 # optional - Guest portal HTTPS redirect port
      - 8880:8880 # optional - Guest portal HTTP redirect port
      - 6789:6789 # optional - Mobile throughput/speed test
      # - 5514:5514/udp # optional - Remote syslog capture
      # - 27117:27117/tcp # optional - local-bound database communication
      # UDP 5656-5699 Ports used by AP-EDU broadcasting.
    volumes:
      - ${DOCKERDIR}/unifi/config:/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      UID: ${UID}
      GID: ${GID}
      TZ: ${TZ}
      # MEM_LIMIT: 1024M # Optionally change the Java memory limit (-Xmx) (default is 1024M).
      # MEM_STARTUP: 1024M # Optionally change the Java initial memory (-Xms) (default is 1024M).
    labels:
      - "traefik.enable=true"
      ## HTTP Routers Auth
      - "traefik.http.routers.unifi-rtr.entrypoints=https"
      - "traefik.http.routers.unifi-rtr.rule=Host(`unifi.$DOMAINNAME`)"
      - "traefik.http.routers.unifi-rtr.priority=99"
      ## Middlewares
      - "traefik.http.routers.unifi-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.unifi-rtr.tls=true"
      - "traefik.http.routers.unifi-rtr.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.unifi-rtr.service=unifi-svc"
      - "traefik.http.services.unifi-svc.loadbalancer.server.scheme=https"
      - "traefik.http.services.unifi-svc.loadbalancer.server.port=8443"
