#######################################
### THIS FILE IS MANAGED BY ANSIBLE ###
###    PLEASE MAKE CHANGES THERE    ###
#######################################

version: "3.7"
services:

  # WatchTower - Automatic Docker Container Updates
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    hostname: watchtower
    restart: unless-stopped
    networks:
      - default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: $TZ
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_REMOVE_VOLUMES: "true"
      WATCHTOWER_INCLUDE_STOPPED: "true"
      WATCHTOWER_NO_STARTUP_MESSAGE: "false"
      WATCHTOWER_SCHEDULE: "0 0 2 * * *" # Everyday at 2am -> https://pkg.go.dev/github.com/robfig/cron@v1.2.0#hdr-CRON_Expression_Format
      WATCHTOWER_NOTIFICATIONS: email
      # WATCHTOWER_NOTIFICATIONS_LEVEL: info  # info is the default
      WATCHTOWER_NOTIFICATION_EMAIL_FROM: $GMAIL_ADDRESS
      WATCHTOWER_NOTIFICATION_EMAIL_TO: $GMAIL_ADDRESS   # Same is fine
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER: smtp.gmail.com
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: 587
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER: $GMAIL_ADDRESS
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD: $GMAIL_PASS
      WATCHTOWER_NOTIFICATION_EMAIL_DELAY: 2
      DOCKER_API_VERSION: "1.40"
