---
# Use this file to store secrets like usernames and passwords.
# Learn more at https://www.home-assistant.io/docs/configuration/secrets/

# Use this tool (https://latlongdata.com/elevation/), find your place and copy your values below:
home_name: {{ hass_home_name }}
latitude_home: {{ hass_latitude_home }}
longitude_home: {{ hass_longitude_home }}
elevation: {{ hass_elevation }}
time_zone: {{ tz }}
currency: {{ hass_currency }}

external_url: "https://hass.{{ domain_name }}"
internal_url: "http://{{ docker_ip }}:8123"

# Mariadb URL - @docker_ip because hass in docker has host networking. Change as desired.
mariadb_url: mysql://{{ mariadb_user }}:{{ mariadb_password }}@{{ docker_ip }}:{{ mariadb_port }}/{{ mariadb_database }}?charset=utf8mb4

# List of trusted proxies, consisting of IP addresses or networks,
# that are allowed to set the X-Forwarded-For header.
# Can be a subnet, e.g. 10.x.x.x/24
http_trusted_proxies:
{% for trusted_proxy in hass_http_trusted_proxies %}
  - "{{ trusted_proxy }}"
{% endfor %}

local_network_lan: "{{ local_network_lan }}"
local_network_homelab: "{{ local_network_homelab }}"

# My PC static IP address
pc_host: "{{ hass_pc_host }}"
docker_host: "{{ docker_ip }}"
influxdb_bucket: "{{ influxdb_hass_bucket_name }}"
influxdb_port: "{{ influxdb_port }}"
influxdb_auth_token: "{{ influxdb_hass_token }}"
# This is in the URL after /orgs
influxdb_organization: "{{ influxdb_org_id }}"
influxdb_glob_entities:
{% for glob_entity in hass_influxdb_glob_entities %}
  - "{{ glob_entity }}"
{% endfor %}

# Google Project ID - This used to be valid jinja, reuse if you want google re-integrated.
# google_project_id: "{ hass_google_project_id }"

# MQTT broker username/password for the docker container:
mqtt_username: "{{ hass_mqtt_username }}"
mqtt_password: "{{ hass_mqtt_password }}"
mqtt_port: "{{ mosquitto_http_port }}"
