---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: arc-homelab
  namespace: actions-runner-system
spec:
  interval: 1h
  chart:
    spec:
      chart: gha-runner-scale-set
      version: 0.7.0
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllerServiceAccount:
      name: actions-runner-controller-gha-rs-controller
    runnerScaleSetName: arc-runner-set-homelab
    githubConfigUrl: https://github.com/samis-group/homelab
    minRunners: 1
    maxRunners: 3
    containerMode:
      type: dind
    template:
      spec:
        containers:
          - name: runner
            image: ghcr.io/actions/actions-runner:2.311.0
            command: ["/home/runner/run.sh"]
            securityContext:
              privileged: true
            volumeMounts:
              - name: daemon-json
                mountPath: /etc/docker/daemon.json
                readOnly: true
              - name: work
                mountPath: /home/runner/_work
              - name: dind-cert
                mountPath: /certs/client
              - name: dind-externals
                mountPath: /home/runner/externals
            # Going to have to mount it like this instead:
            # https://github.com/actions/actions-runner-controller/discussions/2993#discussioncomment-7290987
            # dockerMTU: 1450
        volumes:
          - name: daemon-json
            configMap:
              name: docker-daemon-config
          - name: work
            emptyDir: {}
          - name: dind-cert
            emptyDir: {}
          - name: dind-externals
            emptyDir: {}
  valuesFrom:
    - kind: Secret
      name: actions-runner-controller-auth-secret
      valuesKey: GITHUB_APP_ID
      targetPath: githubConfigSecret.github_app_id
    - kind: Secret
      name: actions-runner-controller-auth-secret
      valuesKey: GITHUB_APP_INSTALLATION_ID
      targetPath: githubConfigSecret.github_app_installation_id
    - kind: Secret
      name: actions-runner-controller-auth-secret
      valuesKey: GITHUB_APP_PRIVATE_KEY
      targetPath: githubConfigSecret.github_app_private_key
