---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Provider
metadata:
  name: discord
  namespace: kube-system
spec:
  channel: homelab
  secretRef:
    name: discord-webhook
  type: discord
  username: FluxBot
