---
#######################################
### THIS FILE IS MANAGED BY ANSIBLE ###
###    PLEASE MAKE CHANGES THERE    ###
#######################################

version: "3.7"

########################### EXTENSION FIELDS

# To use this put this block in your service: "<<: *logging"
x-logging: &logging
  logging:
    driver: loki
    options:
      loki-url: "http://${SERVER_IP}:${LOKI_PORT}/loki/api/v1/push"

########################### NETWORKS

networks:
  traefik_proxy:
    name: traefik_proxy
    external: true

########################### SERVICES

services:
  # MKVToolNix - Video Editing (Remuxing - changing media container while keeping original source quality)
  # https://hub.docker.com/r/jlesage/mkvtoolnix
  mkvtoolnix:
    container_name: mkvtoolnix
    image: jlesage/mkvtoolnix:latest
    init: true
    restart: unless-stopped
    healthcheck:
      test: nc -z localhost 5800
      interval: 60s
      timeout: 3s
      retries: 3
    networks:
      traefik_proxy:
    # ports:
    #   - "$MKVTOOLNIX_PORT:5800"
    volumes:
      - ${USERDIR}/mount/downloads:/data/downloads
      - ${DOCKERDIR}/mkvtoolnix/config:/config:rw
    environment:
      USER_ID: ${PUID}
      GROUP_ID: ${PGID}
      TZ: ${TZ}
      UMASK: 002
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.mkvtoolnix-rtr.entrypoints=https"
      - "traefik.http.routers.mkvtoolnix-rtr.rule=Host(`mkvtoolnix.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.mkvtoolnix-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.mkvtoolnix-rtr.service=mkvtoolnix-svc"
      - "traefik.http.services.mkvtoolnix-svc.loadbalancer.server.port=5800"
    <<: *logging
