---
#######################################
### THIS FILE IS MANAGED BY ANSIBLE ###
###    PLEASE MAKE CHANGES THERE    ###
#######################################

version: "3.7"

########################### EXTENSION FIELDS

# To use this put this block in your service: "<<: *logging"
x-logging: &logging
  logging:
    driver: loki
    options:
      loki-url: "http://${SERVER_IP}:${LOKI_PORT}/loki/api/v1/push"

########################### NETWORKS

networks:
  traefik_proxy:
    name: traefik_proxy
    external: true

########################### SECRETS

secrets:
  plex_claim:
    file: ${DOCKERDIR}/secrets/plex_claim

########################### SERVICES

services:
  # Plex - Media Server
  # https://hub.docker.com/r/plexinc/pms-docker
  plexms:
    container_name: plexms
    image: plexinc/pms-docker:plexpass
    restart: always
    healthcheck:
      test: curl -sI http://localhost:32400
      interval: 60s
      timeout: 3s
      retries: 3
    networks:
      traefik_proxy:
        ipv4_address: 192.168.90.150 # You can specify a static IP - I also created a non-proxied DNS record like 'plex-dc.domain.com' pointing to this IP so i don't need to reference this all the time.
    devices:
      - /dev/dri:/dev/dri # for harware transcoding
    security_opt:
      - no-new-privileges:true
    ports:
      - "${PLEX_PORT}:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp" # conflicts with unifi
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
      #- "$PLEX_WEB_TOOLS_PORT:33400"
    volumes:
      - ${DOCKERDIR}/plexms:/config
      - ${USERDIR}/mount/video:/data
      - /dev/shm:/transcode # Offload transcoding to RAM if you have enough RAM. Otherwise, disk:
      # Optional: separate volumes as it's where I'll be storing metadata to severely reduce the space required when I backup these containers
      - ${DOCKERDIR}/shared/plexms/Library/Application Support/Plex Media Server/Cache:/config/Library/Application Support/Plex Media Server/Cache
      - ${DOCKERDIR}/shared/plexms/Library/Application Support/Plex Media Server/Metadata:/config/Library/Application Support/Plex Media Server/Metadata
      - ${DOCKERDIR}/shared/plexms/Library/Application Support/Plex Media Server/Media:/config/Library/Application Support/Plex Media Server/Media
    environment:
      PLEX_UID: ${PUID}
      PLEX_GID: ${PGID}
      TZ: ${TZ}
      HOSTNAME: "DockerPlex"
      PLEX_CLAIM_FILE: /run/secrets/plex_claim
      ADVERTISE_IP: http://${SERVER_IP}:32400/
    secrets:
      # Grab claim from -> https://www.plex.tv/claim/
      - plex_claim
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.plexms-rtr.entrypoints=https"
      - "traefik.http.routers.plexms-rtr.rule=Host(`plex.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.plexms-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.plexms-rtr.service=plexms-svc"
      - "traefik.http.services.plexms-svc.loadbalancer.server.port=32400"
    <<: *logging
