---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - ./namespace.yaml
  - ./grafana/kustomization.yaml
  - ./unifi-poller/kustomization.yaml
  - ./kube-prometheus-stack/kustomization.yaml
