---
# Might need work. Resource -> https://github.com/ansible-collections/community.windows/blob/main/docs/community.windows.win_credential_module.rst
- name: Add NAS credentials to Windows Credentials Store
  community.windows.win_credential:
    name: "{{ nas.ip }}"
    type: generic_password
    username: "{{ nas.user }}"
    secret: "{{ nas.password }}"
    state: present
