---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: doppler
  namespace: default
spec:
  chart:
    spec:
      chart: doppler-kubernetes-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: doppler
  interval: 5m0s
