#######################################
### THIS FILE IS MANAGED BY ANSIBLE ###
###    PLEASE MAKE CHANGES THERE    ###
#######################################

version: '3.7'

services:

  # Motioneye NVR Surveillance Software
  # Install in docker instructions -> https://github.com/ccrisan/motioneye/wiki/Install-In-Docker
  # Docket hub -> https://hub.docker.com/r/ccrisan/motioneye/
  motioneye:
    container_name: motioneye
    image: "ccrisan/motioneye:master-amd64"
    restart: always
    # user: root
    networks:
      traefik_proxy:
        ipv4_address: 192.168.90.156 # You can specify a static IP
    ports:
      - 8765:8765
    deploy:
      resources:
        limits:
          cpus: '2'
          # memory: 50M
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${DOCKERDIR}/motioneye/etc:/etc/motioneye"
      - "${USERDIR}/mount/motioneye:/var/lib/motioneye"
    environment:
      TZ: ${TZ}
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.motioneye-rtr.entrypoints=https"
      - "traefik.http.routers.motioneye-rtr.rule=Host(`motioneye.$DOMAINNAME`, `cam.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.motioneye-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.motioneye-rtr.service=motioneye-svc"
      - "traefik.http.services.motioneye-svc.loadbalancer.server.port=8765"
