---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: default
spec:
  # ipFamilyPolicy: PreferDualStack
  selector:
    app: api
  ports:
    - name: http
      port: 3000
      targetPort: 3000
