---
#######################################
### THIS FILE IS MANAGED BY ANSIBLE ###
###    PLEASE MAKE CHANGES THERE    ###
#######################################

version: "3.7"

########################### SERVICES

services:
  # Cloudflare DDNS - Dynamic DNS Updater to update my WAN IP if it ever changes
  # https://hub.docker.com/r/oznu/cloudflare-ddns/
  cf-ddns:
    container_name: cf-ddns
    image: oznu/cloudflare-ddns:latest
    init: true
    restart: always
    healthcheck:
      test: ps aux | grep -q [c]rond  # container is a cron job
      interval: 60s
      timeout: 3s
      retries: 3
    security_opt:
      - no-new-privileges:true
    environment:
      API_KEY: $CLOUDFLARE_API_TOKEN
      ZONE: $DOMAINNAME
      PROXIED: "true"
      RRTYPE: A
      DELETE_ON_STOP: "false"
      DNS_SERVER: 1.1.1.1
