---
#######################################
### THIS FILE IS MANAGED BY ANSIBLE ###
###    PLEASE MAKE CHANGES THERE    ###
#######################################

version: "3.7"

########################### NETWORKS

networks:
  traefik_proxy:
    name: traefik_proxy
    external: true

########################### SERVICES

services:
  # https://hub.docker.com/r/grafana/loki
  loki:
    container_name: loki
    image: grafana/loki:2.3.0
    init: true
    restart: always
    healthcheck:
      test: nc -z localhost 3100
      interval: 60s
      timeout: 3s
      retries: 3
    networks:
      traefik_proxy:
        ipv4_address: 192.168.90.250
    ports:
      - "${LOKI_PORT}:3100"
    volumes:
      - ${DOCKERDIR}/loki/config/:/etc/loki
      - ${DOCKERDIR}/loki/data:/data/loki
    command: -config.file=/etc/loki/loki-config.yaml
