---
#######################################
### THIS FILE IS MANAGED BY ANSIBLE ###
###    PLEASE MAKE CHANGES THERE    ###
#######################################

version: "3.7"

########################### NETWORKS

networks:
  traefik_proxy:
    name: traefik_proxy
    external: true

########################### SERVICES

services:
  promtail:
    container_name: promtail
    image: grafana/promtail:2.4.1
    restart: unless-stopped
    # healthcheck:
    #   test: pidof promtail
    #   interval: 60s
    #   timeout: 3s
    #   retries: 3
    volumes:
      - /var/log:/var/log
      - ${DOCKERDIR}/promtail/etc:/etc/promtail
    ports:
      - "9080:9080" # for http web interface
      - "1514:1514" # for syslog-ng
    command: -config.file=/etc/promtail/config.yml
    networks:
      - traefik_proxy
