---
#######################################
### THIS FILE IS MANAGED BY ANSIBLE ###
###    PLEASE MAKE CHANGES THERE    ###
#######################################

version: "3.7"

########################### NETWORKS

networks:
  socket_proxy:
    name: socket_proxy
    external: true

########################### SERVICES

services:
  # Docker Socket Proxy - Security Enchanced Proxy for Docker Socket
  # https://hub.docker.com/r/tecnativa/docker-socket-proxy
  socket-proxy:
    container_name: socket-proxy
    image: tecnativa/docker-socket-proxy
    init: true
    restart: always
    healthcheck:
      test: nc -z localhost 2375
      interval: 60s
      timeout: 3s
      retries: 3
    networks:
      socket_proxy:
        ipv4_address: 192.168.91.254 # You can specify a static IP - I also created a non-proxied DNS record like 'socket-proxy-dc.domain.com' pointing to this IP so i don't need to reference this all the time.
    privileged: true
    ports:
    - "127.0.0.1:2375:2375" # Port 2375 should only ever get exposed to the internal network. When possible use this line.
    # I use the next line instead, as I want portainer to manage multiple docker endpoints within my home network.
    # - "2375:2375"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - LOG_LEVEL=info # debug,info,notice,warning,err,crit,alert,emerg
      ## Variables match the URL prefix (i.e. AUTH blocks access to /auth/* parts of the API, etc.).
      # 0 to revoke access.
      # 1 to grant access.
      ## Granted by Default
      - EVENTS=1
      - PING=1
      - VERSION=1
      ## Revoked by Default
      # Security critical
      - AUTH=0
      - SECRETS=0
      - POST=1              # Watchtower
      - DELETE=1            # Watchtower
      # GET Optons
      - BUILD=0
      - COMMIT=0
      - CONFIGS=0
      - CONTAINERS=1        # Traefik, portainer, etc.
      - DISTRIBUTION=0
      - EXEC=0
      - IMAGES=1            # Portainer, Watchtower
      - INFO=1              # Portainer
      - NETWORKS=1          # Portainer, Watchtower
      - NODES=0
      - PLUGINS=0
      - SERVICES=1          # Portainer
      - SESSION=0
      - SWARM=0
      - SYSTEM=0
      - TASKS=1             # Portaienr
      - VOLUMES=1           # Portainer
      # POST Options
      - CONTAINERS_CREATE=1 # WatchTower
      - CONTAINERS_START=1  # WatchTower
      - CONTAINERS_UPDATE=1 # WatchTower
      # DELETE Options
      - CONTAINERS_DELETE=1 # WatchTower
      - IMAGES_DELETE=1     # WatchTower
