---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: common-secrets
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
  target:
    name: common-secrets
    creationPolicy: Owner
  data:
    - secretKey: TZ
      remoteRef:
        key: TZ
