---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: home-assistant-config-gcp-sa
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: homelab-dev-container
  target:
    name: home-assistant-config-gcp-sa-secret
    creationPolicy: Owner
  data:
  - secretKey: home-assistant-service-account.json
    remoteRef:
      key: HASS_GOOGLE_SERVICE_ACCOUNT
