---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: home-assistant-secrets
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
  target:
    name: home-assistant-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Home Assistant
        # CAMERA_AUTH: "{{ .CAMERA_AUTH }}"
        # HASS_TOKEN: "{{ .HASS_TOKEN }}"
        SECRET_RECORDER_DB_URL: "postgresql://{{ .POSTGRES_USER }}:{{ .POSTGRES_PASS }}@postgres/{{ .POSTGRES_DB }}"
        LATITUDE: "{{ .HASS_LATITUDE_HOME }}"
        LONGITUDE: "{{ .HASS_LONGITUDE_HOME }}"
        # Postgres Init
        POSTGRES_DB: "{{ .POSTGRES_DB }}"
        POSTGRES_HOST: postgres
        POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        POSTGRES_PASS: "{{ .POSTGRES_PASS }}"
        POSTGRES_USER: "{{ .POSTGRES_USER }}"
  dataFrom:
    - find:
        name:
          regexp: "^HASS"
    - find:
        name:
          regexp: "^POSTGRES"
