---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: doppler-release
  namespace: flux-system
resources:
  - ./doppler-release.yml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: doppler-secret
  namespace: flux-system
resources:
  - ./doppler-secret.yml
spec:
  dependsOn:
    - name: doppler-release
