---
- name: Create directory structure
  ansible.windows.win_file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ img_dir }}"
    - "{{ wsl_install_location }}"

- name: Download ubuntu cloud image
  win_get_url:
    url: "{{ ubuntu_img_url }}"
    dest: "{{ img_dir }}\\{{ ubuntu_img_url | basename }}"

- name: Create default wsl instance from cloud image
  ansible.windows.win_command: wsl --import {{ wsl_instance_name }} {{ wsl_install_location }} {{ img_dir }}\{{ ubuntu_img_url | basename }}

- name: Create default wsl instance from cloud image
  ansible.windows.win_command: wsl --set-default {{ wsl_instance_name }}
  when: wsl_set_default

- name: Setup non-root user
  ansible.windows.win_command: |
    wsl sh -c {{ wsl_instance_name }} "`
      addgroup '{{ main_user }}' \\`
      && adduser --uid '1000' \\`
        --ingroup '{{ main_user }}' \\`
        '{{ main_user }}' \\`
      && usermod --append \\`
        --groups 'admin' \\`
        '{{ main_user }}' `
    "
  when: wsl_set_default

# # setup linux user
# wsl sh -d -c "`
#   addgroup '${user}' \\`
#   && adduser --uid '1000' \\`
#     --ingroup '${user}' \\`
#     '${user}' \\`
#   && usermod --append \\`
#     --groups 'admin' \\`
#     '${user}' `
# "

# # setup default WSL 2 user
# Get-ItemProperty Registry::HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Lxss\*\ DistributionName `
#   | Where-Object -Property DistributionName -eq "Ubuntu-20.04" `
#   | Set-ItemProperty -Name DefaultUid -Value 1000