---
- name: Create directory structure
  ansible.windows.win_file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ img_dir }}"
    - "{{ wsl_install_location }}"

- name: Download ubuntu cloud image
  win_get_url:
    url: "{{ ubuntu_img_url }}"
    dest: "{{ img_dir }}\\{{ ubuntu_img_url | basename }}"

- name: Create wsl instance from cloud image
  ansible.windows.win_command: wsl --import {{ wsl_instance_name }} {{ wsl_install_location }} {{ img_dir }}\{{ ubuntu_img_url | basename }}

- name: Set default wsl instance
  ansible.windows.win_command: wsl --set-default {{ wsl_instance_name }}
  when: wsl_set_default

- name: Setup non-root user
  ansible.windows.win_command: wsl -d {{ wsl_instance_name }} sh -c "addgroup '{{ main_user }}' && adduser --uid '1000' --ingroup '{{ main_user }}' '{{ main_user }}' && usermod --append --groups 'admin' '{{ main_user }}' && echo '{{ main_user }}:{{ ansible_become_password }}' | chpasswd"
  when: wsl_set_default

- name: set default WSL 2 user
  ansible.windows.win_powershell:
    script: |
      Get-ItemProperty Registry::HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Lxss\*\ DistributionName |
      Where-Object -Property DistributionName -eq "{{ wsl_instance_name }}" |
      Set-ItemProperty -Name DefaultUid -Value 1000
