---
- name: Create docker group if non existant
  group:
    name: "{{ docker_group }}"
    state: present

# Create user based on username
- name: Create user and add to docker/sudo groups
  user:
    name: "{{ main_user }}"
    password: "{{ ansible_become_password | password_hash('sha512', 'mysecretsalt') }}"
    groups:
      - "{{ docker_group }}"
      - sudo
    append: true
    state: present
    shell: /bin/bash
    createhome: true
    home: "{{ user_dir }}"
  register: user_created

# Grab UID/GID into vars
- name: set variables UID and GID for user to use in the rest of the playbook
  set_fact:
    puid: "{{ user_created.uid }}"
    pgid: "{{ user_created.group }}"
