---
# get user info
- name: get user info
  user:
    name: "{{ main_user }}"
  register: user_info
  ignore_errors: true

# Grab UID/GID into vars
- name: set variables UID and GID for user to use in the rest of the playbook
  set_fact:
    puid: "{{ user_info.uid  | default('1000') }}"
    pgid: "{{ user_info.group | default('1000') }}"
