---
#######################################
### THIS FILE IS MANAGED BY ANSIBLE ###
###    PLEASE MAKE CHANGES THERE    ###
#######################################

version: "3.7"

########################### EXTENSION FIELDS

# To use this put this block in your service: "<<: *logging"
x-logging: &logging
  logging:
    driver: loki
    options:
      loki-url: "http://${SERVER_IP}:${LOKI_PORT}/loki/api/v1/push"

########################### NETWORKS

networks:
  defaulty:
    name: defaulty
    external: true
  traefik_proxy:
    name: traefik_proxy
    external: true

########################### SERVICES

services:
  # InfluxDB - Database for sensor data
  # Create influxdb.conf
  # https://hub.docker.com/_/influxdb
  influxdb:
    container_name: influxdb
    image: influxdb:latest
    init: true
    restart: always
    healthcheck:
      test: curl -sI http://127.0.0.1:8086
      interval: 60s
      timeout: 3s
      retries: 3
    networks:
      - traefik_proxy
    security_opt:
      - no-new-privileges:true
    ports:
      - "${INFLUXDB_PORT}:8086"
    volumes:
      - ${DOCKERDIR}/appdata/influxdb/config:/etc/influxdb2
      - ${DOCKERDIR}/appdata/influxdb/data:/var/lib/influxdb2
    environment:
      - TZ=${TZ}
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${SERVICES_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${SERVICES_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=home
      - DOCKER_INFLUXDB_INIT_BUCKET=home_assistant
      - DOCKER_INFLUXDB_INIT_RETENTION=26w # Change this to however many weeks you want influxdb to retain data on the initial bucket created. Omit to store data indefinitely.
      # # Logging queries for troubleshooting - DOESN'T CURRENTLY WORK and no idea why? :sadface:
      # - INFLUXDB_DATA_QUERY_LOG_ENABLED=true
      # - INFLUXDB_DATA_TRACE_LOGGING_ENABLED=true
      # - INFLUXDB_HTTP_LOG_ENABLED=true
      # # Log level: error, warn, info, debug
      # - INFLUXDB_LOGGING_LEVEL=debug
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.influxdb-rtr.entrypoints=https"
      - "traefik.http.routers.influxdb-rtr.rule=Host(`influxdb.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.influxdb-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.influxdb-rtr.service=influxdb-svc"
      - "traefik.http.services.influxdb-svc.loadbalancer.server.port=8086"
    <<: *logging

  # phpMyAdmin - Database management
  # https://hub.docker.com/_/phpmyadmin
  # Create a new user with admin privileges. Cannot login as MySQL root for some reason.
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    init: true
    restart: unless-stopped
    networks:
      - traefik_proxy
      - defaulty
    ports:
      - "${PHPMYADMIN_PORT}:80"
    # volumes:
    #   - ${DOCKERDIR}/appdata/phpmyadmin:/etc/phpmyadmin
    environment:
      - PMA_HOST=${SERVER_IP}   # Because mariadb is on host networking
      - PMA_PORT=${MARIADB_PORT}
      #- PMA_ARBITRARY=1  # Allows you to enter a database server hostname on login form.
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.phpmyadmin-rtr.entrypoints=https"
      - "traefik.http.routers.phpmyadmin-rtr.rule=Host(`pma.$DOMAINNAME`, `phpmyadmin.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.phpmyadmin-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.phpmyadmin-rtr.service=phpmyadmin-svc"
      - "traefik.http.services.phpmyadmin-svc.loadbalancer.server.port=80"
    <<: *logging

  # Redis - Key-value Store
  # https://hub.docker.com/_/redis/
  redis:
    container_name: redis
    image: redis:latest
    init: true
    restart: always
    entrypoint: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD} --maxmemory 512mb --maxmemory-policy allkeys-lru
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - defaulty
    volumes:
      - ${DOCKERDIR}/appdata/redis:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    <<: *logging

  # Redis Commander - Redis Management Tool
  # https://hub.docker.com/r/rediscommander/redis-commander/
  rediscommander:
    container_name: rediscommander
    image: rediscommander/redis-commander:latest
    init: true
    restart: always
    ports:
      - "${REDISCOMMANDER_PORT}:8081"
    networks:
      - traefik_proxy
      - defaulty
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.rediscommander-rtr.entrypoints=https"
      - "traefik.http.routers.rediscommander-rtr.rule=Host(`redis.${DOMAINNAME}`)"
      ## Middlewares
      - "traefik.http.routers.rediscommander-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.rediscommander-rtr.service=rediscommander-svc"
      - "traefik.http.services.rediscommander-svc.loadbalancer.server.port=8081"
    <<: *logging
