---
#######################################
### THIS FILE IS MANAGED BY ANSIBLE ###
###    PLEASE MAKE CHANGES THERE    ###
#######################################

version: "3.7"

########################### EXTENSION FIELDS

# To use this put this block in your service: "<<: *logging"
x-logging: &logging
  logging:
    driver: loki
    options:
      loki-url: "http://${SERVER_IP}:${LOKI_PORT}/loki/api/v1/push"

########################### NETWORKS

networks:
  default:
    name: docker_default
    external: true
  traefik_proxy:
    name: traefik_proxy
    external: true

########################### SECRETS

secrets:
  gmail_email:
    file: ${DOCKERDIR}/secrets/gmail_address
  # This gmail password needs to be the APPLICATION password, not your main login one.
  # https://support.google.com/accounts/answer/185833?hl=en
  gmail_app_pass:
    file: ${DOCKERDIR}/secrets/gmail_app_pass
  services_username:
    file: ${DOCKERDIR}/secrets/services_username
  services_password:
    file: ${DOCKERDIR}/secrets/services_password


########################### SERVICES

services:
  # Grafana - Graphical data visualization for InfluxDB data
  # https://hub.docker.com/r/grafana/grafana
  grafana:
    container_name: grafana
    # Using ubuntu image instead of alpine because of the plugin `grafana-image-renderer` only being available on ubuntu. Revert back to `latest` if they fix this -> https://grafana.com/docs/grafana/latest/installation/docker/#build-with-grafana-image-renderer-plugin-pre-installed
    image: grafana/grafana:latest-ubuntu
    restart: always
    healthcheck:
      test: curl -sI http://localhost:3000
      interval: 60s
      timeout: 3s
      retries: 3
    networks:
      traefik_proxy:
        ipv4_address: 192.168.90.151 # You can specify a static IP - I also created a non-proxied DNS record like 'transmission-dc.domain.com' pointing to this IP so i don't need to reference this all the time.
      default: ~
    security_opt:
      - no-new-privileges:true
    ports:
      - "$GRAFANA_PORT:3000"
    user: "0"
    depends_on:
      influxdb:
        condition: service_healthy
    volumes:
      - ${DOCKERDIR}/grafana/data:/var/lib/grafana
      # - ${DOCKERDIR}/grafana/logs:/var/log/grafana  # Logging file when debugging. Disable in prod.
      # Skipped to using environment vars below instead of mapping config.ini
      # - ${DOCKERDIR}/grafana/config/grafana.ini:/etc/grafana/grafana.ini # Mount the grafana config as well to make changes to it.
    secrets:
      - gmail_email
      - gmail_app_pass
      - services_username
      - services_password
    environment:
      # I use ENV vars instead of mapping the config file - RTFM on how to set them up for ANY config:
      # https://grafana.com/docs/grafana/latest/administration/configuration/#override-configuration-with-environment-variables
      TZ: ${TZ}
      # Add plugin from github like: https://github.com/Aryido/grafana-jsontext-panel/releases/download/v1.2.2-beta/fondus-jsonpretty-panel.zip; fondus-jsonpretty-panel
      GF_INSTALL_PLUGINS: "grafana-image-renderer,grafana-clock-panel,grafana-simple-json-datasource,grafana-worldmap-panel,grafana-piechart-panel"
      # GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: fondus-jsonpretty-panel    # https://github.com/Fondus/Grafana-JsonPretty-Panel#faq
      # Some config items:
      GF_SERVER_DOMAIN: "grafana.${DOMAINNAME}"
      GF_SERVER_ROOT_URL: "https://grafana.${DOMAINNAME}"
      # Admin User setup
      GF_SECURITY_ADMIN_USER__FILE: "/run/secrets/services_username"
      GF_SECURITY_ADMIN_PASSWORD__FILE: "/run/secrets/services_password"
      # Home Assistant iframe integration (we use google oauth in front of everything on the reverse proxy, so we should be fine)
      # GF_AUTH_DISABLE_LOGIN_FORM: "true"
      # GF_AUTH_ANONYMOUS_ENABLED: "true"
      # GF_AUTH_ANONYMOUS_ORG_ROLE: "Viewer"
      # GF_SECURITY_ALLOW_EMBEDDING: "true"
      # Using Gmail SMTP for alerts
      GF_SMTP_ENABLED: "true"
      GF_SMTP_HOST: "smtp.gmail.com:587"
      GF_SMTP_SKIP_VERIFY: "true"
      GF_SMTP_FROM_NAME: "Grafana"
      GF_SMTP_FROM_ADDRESS: "admin@grafana.${DOMAINNAME}"
      GF_SMTP_USER__FILE: "/run/secrets/gmail_email"
      GF_SMTP_PASSWORD__FILE: "/run/secrets/gmail_app_pass"
      # Grafana 8 alerting enable
      GF_UNIFIED_ALERTING_ENABLED: "true"
      GF_ALERTING_ENABLED: "false"
      # Log level/mode - Disable all logging env vars in prod (https://grafana.com/docs/grafana/latest/administration/configuration/#log)
      # GF_LOG_MODE: "console file" # Log to both console and file.
      # GF_LOG_LEVEL: "debug"
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.grafana-rtr.entrypoints=https"
      - "traefik.http.routers.grafana-rtr.rule=Host(`grafana.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.grafana-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.grafana-rtr.service=grafana-svc"
      - "traefik.http.services.grafana-svc.loadbalancer.server.port=3000"
    <<: *logging
