---
#######################################
### THIS FILE IS MANAGED BY ANSIBLE ###
###    PLEASE MAKE CHANGES THERE    ###
#######################################

version: "3.7"

########################### EXTENSION FIELDS

# To use this put this block in your service: "<<: *logging"
x-logging: &logging
  logging:
    driver: loki
    options:
      loki-url: "http://${SERVER_IP}:${LOKI_PORT}/loki/api/v1/push"

########################### NETWORKS

networks:
  traefik_proxy:
    name: traefik_proxy
    external: true

########################### SERVICES

services:
  # NordVPN
  # https://hub.docker.com/r/bubuntux/nordlynx
  nordlynx:
    container_name: nordlynx
    image: ghcr.io/bubuntux/nordlynx
    restart: always
    cap_add:
      - NET_ADMIN   # required
    networks:
      - traefik_proxy
    ports:
      - ${QBITTORRENT_PORT}:${QBITTORRENT_PORT}   # qbittorrent
      - ${TRANSMISSION_PORT}:9091   # Transmission
      - 51413:51413                 # Transmission
      - 51413:51413/udp             # Transmission
    environment:
      PRIVATE_KEY: ${NORDVPN_PRIVATE_KEY} # required
      DNS: "1.1.1.1,8.8.8.8,1.0.0.1"
      NET_LOCAL: ${LOCAL_NETWORK}
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1  # Recomended if using ipv4 only
    <<: *logging
