---
#######################################
### THIS FILE IS MANAGED BY ANSIBLE ###
###    PLEASE MAKE CHANGES THERE    ###
#######################################

version: "3.7"

########################### SERVICES

services:
  # Repo here -> https://gitlab.com/sami-group/ozbargain_bot
  # This ozbargain bot sends ozbargain deals to slack and discord using incoming webhooks.
  ozbargain:
    image: registry.gitlab.com/sami-group/ozbargain_bot:latest
    init: true
    user: ${PUID}:${PGID}
    container_name: ozbargain
    restart: unless-stopped
    volumes:
      - "${DOCKERDIR}/appdata/ozbargain:/config"
    environment:
      OZBARGAIN_SLACK_WEBHOOK: ${OZBARGAIN_SLACK_WEBHOOK}
      OZBARGAIN_SLACK_WEBHOOK_FRONTPAGE: ${OZBARGAIN_SLACK_WEBHOOK_FRONTPAGE}
