---
#######################################
### THIS FILE IS MANAGED BY ANSIBLE ###
###    PLEASE MAKE CHANGES THERE    ###
#######################################

version: "3.7"

########################### EXTENSION FIELDS

# Default TZ, uid and pid
# To use this put this block in your service: "<<: *default-tz-uid-gid"
x-environment: &default-tz-uid-gid
  TZ: $TZ
  PUID: $PUID
  PGID: $PGID

# To use this put this block in your service: "<<: *logging"
x-logging: &logging
  logging:
    driver: loki
    options:
      loki-url: "http://${SERVER_IP}:${LOKI_PORT}/loki/api/v1/push"

########################### SERVICES

services:
  # qBittorrent - Torrent downloader
  # https://hub.docker.com/r/linuxserver/qbittorrent
  # Needs trailing / if using PathPrefixStrip
  qbittorrent:
    container_name: qbittorrent
    image: linuxserver/qbittorrent:latest
    restart: always
    healthcheck:
      test: curl -sI http://localhost:${QBITTORRENT_PORT}
      interval: 60s
      timeout: 3s
      retries: 3
    network_mode: service:nordlynx
    depends_on:
      - nordlynx
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${DOCKERDIR}/qbittorrent:/config
      - ${USERDIR}/mount/downloads:/downloads
    environment:
      <<: *default-tz-uid-gid
      # UMASK: 002
      WEBUI_PORT: ${QBITTORRENT_PORT}
    # ports:
    #   - 8168:8168   # Web UI
    #   - 6881:6881
    #   - 6881:6881/udp
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.qbittorrent-rtr.entrypoints=https"
      - "traefik.http.routers.qbittorrent-rtr.rule=Host(`qbit.$DOMAINNAME`, `qbittorrent.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.qbittorrent-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.qbittorrent-rtr.service=qbittorrent-svc"
      - "traefik.http.services.qbittorrent-svc.loadbalancer.server.port=${QBITTORRENT_PORT}"
    <<: *logging
