---
#######################################
### THIS FILE IS MANAGED BY ANSIBLE ###
###    PLEASE MAKE CHANGES THERE    ###
#######################################

version: "3.7"

########################### EXTENSION FIELDS

# To use this put this block in your service: "<<: *logging"
x-logging: &logging
  logging:
    driver: loki
    options:
      loki-url: "http://${SERVER_IP}:${LOKI_PORT}/loki/api/v1/push"

########################### NETWORKS

networks:
  default:
    name: docker_default
    external: true
  traefik_proxy:
    name: traefik_proxy
    external: true

########################### SERVICES

services:
  # Redis Commander - Redis Management Tool
  # https://hub.docker.com/r/rediscommander/redis-commander/
  rediscommander:
    container_name: rediscommander
    image: rediscommander/redis-commander:latest
    restart: always
    ports:
      - "${REDISCOMMANDER_PORT}:8081"
    networks:
      - traefik_proxy
      - default
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.rediscommander-rtr.entrypoints=https"
      - "traefik.http.routers.rediscommander-rtr.rule=Host(`redis.${DOMAINNAME}`)"
      ## Middlewares
      - "traefik.http.routers.rediscommander-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.rediscommander-rtr.service=rediscommander-svc"
      - "traefik.http.services.rediscommander-svc.loadbalancer.server.port=8081"
    <<: *logging
