---
#######################################
### THIS FILE IS MANAGED BY ANSIBLE ###
###    PLEASE MAKE CHANGES THERE    ###
#######################################

version: "3.7"

########################### EXTENSION FIELDS

# Default TZ, uid and pid
# To use this put this block in your service: "<<: *default-tz-uid-gid"
x-environment: &default-tz-uid-gid
  TZ: $TZ
  PUID: $PUID
  PGID: $PGID

# To use this put this block in your service: "<<: *logging"
x-logging: &logging
  logging:
    driver: loki
    options:
      loki-url: "http://${SERVER_IP}:${LOKI_PORT}/loki/api/v1/push"

########################### SERVICES

services:
  # Transmission for *arr apps
  # https://hub.docker.com/r/linuxserver/transmission/
  transmission:
    container_name: transmission
    image: lscr.io/linuxserver/transmission
    restart: always
    network_mode: service:nordlynx
    depends_on:
      - nordlynx
    environment:
      <<: *default-tz-uid-gid
      TRANSMISSION_WEB_HOME: /transmission-web-control/   # optional theme
      # WHITELIST: ${LOCAL_NETWORK}   # optional
      # - HOST_WHITELIST=dnsnane list #optional
      # - USER=username #optional
      # - PASS=password #optional
    volumes:
      - ${DOCKERDIR}/transmission/config:/config
      - ${USERDIR}/mount/downloads:/downloads
      - ${DOCKERDIR}/transmission/watch:/watch
      - /etc/localtime:/etc/localtime:ro
    # ports:
    #   - ${TRANSMISSION_PORT}:9091
    #   - 51413:51413
    #   - 51413:51413/udp
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.transmission-vpn-rtr.entrypoints=https"
      - "traefik.http.routers.transmission-vpn-rtr.rule=Host(`transmission.$DOMAINNAME`, `torrent.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.transmission-vpn-rtr.middlewares=chain-oauth@file"  # Testing oauth
      # - "traefik.http.routers.transmission-vpn-rtr.middlewares=middlewares-rate-limit@file" # If oauth doesn't work because it uses a vpn, we need to at least rate limit
      ## HTTP Services
      - "traefik.http.routers.transmission-vpn-rtr.service=transmission-vpn-svc"
      - "traefik.http.services.transmission-vpn-svc.loadbalancer.server.port=9091"
    <<: *logging
