---
#######################################
### THIS FILE IS MANAGED BY ANSIBLE ###
###    PLEASE MAKE CHANGES THERE    ###
#######################################

version: "3.7"

########################### EXTENSION FIELDS

# To use this put this block in your service: "<<: *logging"
x-logging: &logging
  logging:
    driver: loki
    options:
      loki-url: "http://${SERVER_IP}:${LOKI_PORT}/loki/api/v1/push"

########################### SERVICES

services:
  # zigbee2mqtt
  # https://hub.docker.com/r/koenkk/zigbee2mqtt/
  # You also need to add home assistant -> https://github.com/zigbee2mqtt/hassio-zigbee2mqtt
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:latest
    restart: always
    network_mode: host
    user: ${PUID}:${PGID}
    healthcheck:
      test: nc -z localhost ${ZIGBEE2MQTT_PORT}
      interval: 60s
      timeout: 3s
      retries: 3
    # To add this container to the 'dialout' group so it can use the device - ll /dev/ttyACM0 (or whatever your device location is)
    group_add:
      - dialout
    ports:
      # Frontend port
      - ${ZIGBEE2MQTT_PORT}:${ZIGBEE2MQTT_PORT}
    environment:
      - TZ=${TZ}
    volumes:
      - ${DOCKERDIR}/zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro 
    devices:
      # This is the conbee device mapping
      - "${ZIGBEE_ADAPTER_TTY}:/dev/ttyZigbee"
    privileged: true
    <<: *logging
