---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-movies
  namespace: default
spec:
  storageClassName: ""
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.10.0.2
    path: /volume1/docker/data/media/movies
    readOnly: false
