---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: actions-runner-controller-auth
  namespace: actions-runner-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: homelab-dev-container
  target:
    name: actions-runner-controller-auth-secret
    creationPolicy: Owner
  dataFrom:
    - find:
        name:
          regexp: "GITHUB_APP"
