#######################################
### THIS FILE IS MANAGED BY ANSIBLE ###
###    PLEASE MAKE CHANGES THERE    ###
#######################################

http:
  routers:
    zigbee2mqtt-rtr:
      rule: "Host(`zigbee.{{ domain_name }}`)"
      entryPoints:
        - https
      middlewares:
        - chain-oauth
        # - chain-authelia
        # - zigbee2mqtt-add-admin  # Uncomment if you need the path prefix addition below
      service: zigbee2mqtt-svc
      tls:
        certResolver: dns-cloudflare
  # Add this section if you need a prefix (remember to uncomment the middleware in the router above as well)
  # middlewares:
  #   zigbee2mqtt-add-admin:
  #     addPrefix: 
  #       prefix: "/index.php"
  services:
    zigbee2mqtt-svc:
      loadBalancer:
        servers:
          - url: "http://{{ docker_ip }}:{{ zigbee2mqtt_port }}"  # or whatever your external host's IP:port is
