---
##############
### Gitlab ###
##############

# Resource -> https://codereview.stackexchange.com/questions/175616/clone-a-gitlab-private-repo-with-ansible

- name: Make sure {{ main_user }} has ssh key
  user:
    name: "{{ main_user }}"
    generate_ssh_key: yes
    ssh_key_file: "{{ user_dir }}/.ssh/{{ main_user_ssh_key_prefix ~ inventory_hostname_short }}"

# TODO: Needs checking of fingerprint, remove key if not same
- name: Check if GitLab has this user's SSH key
  uri:
    url: "{{ gitlab.api_url }}/user/keys"
    method: GET
    status_code: [200]
    headers:
      private-token: "{{ gitlab.personal_access_token }}"
      Content-Type: "application/json"
  register: user_ssh_keys

- name: debug user_ssh_keys
  debug:
    var: user_ssh_keys

- name: Assign ssh key to a variable
  shell:
    cat {{ user_dir }}/.ssh/{{ main_user_ssh_key_prefix ~ inventory_hostname_short }}.pub
  register: deployer_user_public_key
  when: not user_ssh_keys.json | selectattr('title', 'equalto', main_user_ssh_key_prefix ~ inventory_hostname_short) | list | length > 0

- name: Push the generated ssh key to the GitLab instance
  uri:
      url: "{{ gitlab.api_url }}/user/keys"
      method: POST
      status_code: [201, 400]
      headers:
        private-token: "{{ gitlab.personal_access_token }}"
        Content-Type: "application/json"
      body: >
        {
          "title": "{{ main_user_ssh_key_prefix ~ inventory_hostname_short }}", 
          "key": "{{ deployer_user_public_key.stdout_lines.0 }}"
        }
      body_format: json
  when: not user_ssh_keys.json | selectattr('title', 'equalto', main_user_ssh_key_prefix ~ inventory_hostname_short) | list | length > 0

- name: Ensure .ssh/config file exists
  file:
    state: touch
    path: "{{ user_dir }}/.ssh/config"
  when: not user_ssh_keys.json | selectattr('title', 'equalto', main_user_ssh_key_prefix ~ inventory_hostname_short) | list | length > 0

- name: Disable host key checking
  lineinfile:
    path: "{{ user_dir }}/.ssh/config"
    line: "Host *\n \tStrictHostKeyChecking no\n\tUserKnownHostsFile=/dev/null"
    regexp: '^Host \*$'
  when: not user_ssh_keys.json | selectattr('title', 'equalto', main_user_ssh_key_prefix ~ inventory_hostname_short) | list | length > 0

- name: Add deploy group to sudoers file and validate
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%{{ docker_group }}'
    line: '%{{ docker_group }} ALL=(ALL) NOPASSWD:ALL'
    validate: "visudo -cf %s"

- name: Checkout docker containers source code
  git: 
    repo: "{{ item.value }}"
    dest: "{{ docker_dir }}/appdata/{{ item.key }}"
    key_file: "{{ user_dir }}/.ssh/{{ main_user_ssh_key_prefix ~ inventory_hostname_short }}"
    accept_hostkey: true
  with_dict: "{{ gitlab.clone_repos }}"
  register: git_checkout_code
  ignore_errors: true   # Because Home assistant gets changed to, and realistically, this only needs to be run initially anyway.
  become: false

- name: Touch home-assistant.log for hacs to install as it's install script requires this file to exist
  file:
    path: "{{ docker_dir }}/appdata/hass/home-assistant.log"
    state: touch
    owner: "{{ main_user }}"
    group: "{{ docker_group }}"
    mode: '0644'
