---
- name: Apt Upgrade
  apt:
    name: '*'
    state: latest
    update_cache: true

- name: Install required packages
  apt:
    state: present
    pkg:
      - wget
      - telnet
      - net-tools
      - logrotate
      - htop
      - make
      - vim
      - python3
      - python3-pip
      - cifs-utils
      - nfs-common
      - bash-completion
      - apt-transport-https
      - software-properties-common
      - jq
      - git
      - conntrack

- name: pip self-update
  pip:
    name: pip
    state: latest

- name: Install doppler cli tools
  ansible.builtin.shell: curl -Ls --tlsv1.2 --proto "=https" --retry 3 https://cli.doppler.com/install.sh | sh
