---
- name: Gather all facts of cloud init
  community.general.cloud_init_data_facts:
  register: ci_result
  delegate_to: "{{ vm.ip_address | default(inventory_hostname) }}"

- name: Wait for cloud init to finish
  community.general.cloud_init_data_facts:
    filter: status
  register: res
  delegate_to: "{{ vm.ip_address | default(inventory_hostname) }}"
  until: "res.cloud_init_data_facts.status.v1.stage is defined and not res.cloud_init_data_facts.status.v1.stage"
  retries: 100
  delay: 5
