---
- name: Apt Upgrade
  apt:
    name: '*'
    state: latest
    update_cache: true

# apt install lm-sensors watch sudo nvme-cli telegraf
- name: Install required packages for telegraf
  apt:
    state: latest
    pkg:
    - lm-sensors
    - watch
    - sudo
    - nvme-cli
    - telegraf
  # systemctl restart pvestatd
  notify: restart pvestatd
