---
- name: Apt Upgrade
  apt:
    name: '*'
    state: latest
    update_cache: true

- name: Install required packages on proxmox hosts
  apt:
    state: latest
    pkg:
    # - lm-sensors
    - watch
    - sudo
    - python3-pip
    # - nvme-cli
    # - telegraf
  # notify: restart pvestatd

- name: Install required pip modules on proxmox host(s)
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - proxmoxer
    - requests
