---
- name: Setup cloudflare DNS for VM's
  community.general.cloudflare_dns:
    zone: "{{ domain_name }}"
    record: "{{ vm.name }}"
    type: A
    value: "{{ vm.ip_address }}"
    api_token: "{{ cloudflare_api_token }}"

- name: Clone template to new VM's
  proxmox_kvm:
    node: "{{ pve.proxmox_node }}"
    api_user: "{{ pve.proxmox_api_user }}"
    api_password: "{{ pve.proxmox_api_pass }}"
    api_host: "{{ proxmox_ip }}"
    clone: "{{ vm.template | default(vm_defaults.template) }}"
    full: "yes"
    name: "{{ vm.name }}"
    storage: "{{ vm.storage | default(vm_defaults.storage) }}" 
    timeout: "{{ pve.clone_timeout }}"
    ipconfig:
      ipconfig0: "ip={{ vm.ip_address }}/{{ vm_defaults.netmask }},gw={{ vm_defaults.gateway }}"
    boot: "{{ vm.boot_order | default(vm_defaults.boot_order) }}"
    bootdisk: "{{ vm.boot_disk | default(vm_defaults.boot_disk) }}"
    newid: "{{ vm.id }}"
    ciuser: "{{ vm.user | default(vm_defaults.user) }}"
    cipassword: "{{ vm.password | default(vm_defaults.password) }}" # OPTIONAL
    sshkeys: "{{ vm.ssh_key | default(vm_defaults.ssh_key) }}"
    nameservers:
      - "{{ vm.dns1 | default(vm_defaults.dns1) }}"
      - "{{ vm.dns2 | default(vm_defaults.dns2) }}"
    cores: "{{ vm.cores | default(vm_defaults.cores) }}"
    memory: "{{ vm.ram | default(vm_defaults.ram) }}"
  register: cloned_vm

- name: Expand disks for each VM to their configured amount
  shell:
    cmd: "qm resize {{ vm.id }} {{ vm.boot_disk | default(vm_defaults.boot_disk) }} {{ vm.hdd_size | default(vm_defaults.hdd_size) }}"
  when: cloned_vm.changed

- name: Update IP addresses for VM's
  shell:
    cmd: "qm set {{ vm.id }} --ipconfig0 ip={{ vm.ip_address }}/{{ vm_defaults.netmask }},gw={{ vm_defaults.gateway }}"
  when: cloned_vm.changed
