---
# Issue with this is it is not updating the cloud-init values per machine once it's cloned. Not sure why?
# Could be related to the below commented out code bits, explaining you need to boot up the machine, shutdown, then you can change IP.
# I was able to change IP with this command, just need to loop all vm's and apply:
# qm set 202 --ipconfig0 'ip=10.10.0.22/24,gw=10.10.0.1'

- name: Clone template to new VM's
  proxmox_kvm:
    node: "{{ pve.proxmox_node }}"
    api_user: "{{ pve.proxmox_api_user }}"
    api_password: "{{ pve.proxmox_api_pass }}"
    api_host: "{{ proxmox_ip }}"
    clone: "{{ item.value.template }}"
    full: "yes"
    name: "{{ item.value.name }}"
    storage: "{{ item.value.storage | default(vms_def.storage) }}" 
    timeout: "{{ pve.clone_timeout }}"
    ipconfig:
      ipconfig0: "ip={{ item.value.ip_address }}/{{ vms_def.netmask }},gw={{ vms_def.gateway }}"
    boot: "{{ item.value.boot_order | default(vms_def.boot_order) }}"
    bootdisk: "{{ item.value.boot_disk | default(vms_def.boot_disk) }}"
    newid: "{{ item.value.vmid }}"
    ciuser: "{{ item.value.user | default(vms_def.user) }}"
    cipassword: "{{ item.value.password | default(omit) }}" #OPTIONAL
    sshkeys: "{{ item.value.ssh_key | default(vms_def.ssh_key) }}"
    nameservers:
      - "{{ item.value.dns1| default(vms_def.dns1) }}"
      - "{{ item.value.dns2| default(vms_def.dns2) }}"
    cores: "{{ item.value.cores| default(vms_def.cores) }}"
    memory: "{{ item.value.ram| default(vms_def.ram) }}"
  loop: "{{ vms | dict2items }}"

- name: Expand disks for each VM to their configured amount
  shell:
    cmd: "qm resize {{ item.value.vmid }} scsi0 {{ item.value.hdd_size | default(vms_def.hdd_size) }}"
  loop: "{{ vms | dict2items }}"

- name: Update IP addresses for VM's
  shell:
    cmd: "qm set {{ item.value.vmid }} --ipconfig0 ip={{ item.value.ip_address }}/{{ vms_def.netmask }},gw={{ vms_def.gateway }}"
  loop: "{{ vms | dict2items }}"
