---
- name: 'Start VM'
  proxmox_kvm:
    node: "{{ pve.proxmox_node }}"
    api_user: "{{ pve.proxmox_api_user }}"
    api_password: "{{ pve.proxmox_api_pass }}"
    api_host: "{{ proxmox_ip }}"
    name: "{{ vm.name }}"
    state: started
  when: cloned_vm.changed

- name: Pausing until VM's are started and bootstrapped by cloud-init. Cancel early if console appears quiet on the new VM's. The last entry should show that it "Reached target Cloud-init target".
  pause:
    minutes: 10
