---
- name: 'Start VM'
  proxmox_kvm:
    node: "{{ pve.proxmox_node }}"
    api_user: "{{ pve.proxmox_api_user }}"
    api_password: "{{ pve.proxmox_api_pass }}"
    api_host: "{{ proxmox_ip }}"
    name: "{{ vm.name | default(inventory_hostname_short) }}"
    state: started
  when: cloned_vm.changed

- name: Wait until VM's are started
  wait_for:
    port: 22
    host: "{{ vm_ip_address }}"
    search_regex: OpenSSH
    # Cloud-init bootstraps by apt updating, and doing other bits and Openssh generally comes up before it finishes.
    # we need to give cloud-init time to populate facts to ansible, otherwise it exists early, hence 60s wait before cloud-init check below.
    delay: 60
  delegate_to: localhost
  when: cloned_vm.changed

- name: Check if cloud-init has finished bootstrapping the VM
  include_tasks: tasks/proxmox/check_cloud_init.yml
  when: cloned_vm.changed
